-- =====================================================================
-- ROLLBACK — recria as 4 views de compatibilidade removidas por
-- db/sql/views/DROP_views_compatibilidade.sql.
--
-- Contexto: a reestruturacao de nomenclatura de 27/08/2026 renomeou as
-- tabelas para o padrao sap_/sup_/core_/ops_ e deixou estes 4 nomes vivos
-- como fachada, para nao quebrar cliente com bundle antigo em cache. Tres
-- dias depois, com o codigo ja lendo so as novas fontes e nenhum objeto do
-- banco dependendo delas, as fachadas puderam ser removidas.
--
-- Rode este arquivo INTEIRO se algum consumidor esquecido aparecer. As
-- definicoes sao copia literal do dump 20260827132829_remote_schema.sql,
-- e os GRANTs no fim reproduzem a ACL que elas tinham (acesso total para
-- postgres/anon/authenticated/service_role, security_invoker=true).
-- =====================================================================


-- ----- pedidosforn -----
CREATE OR REPLACE VIEW "public"."pedidosforn" WITH ("security_invoker"='true') AS
 SELECT "id",
    "material",
    "txt_breve",
    "cod_forn",
    "cnpj",
    "fornecedor",
    "regiao_uf",
    "data_pedido",
    "campos_extras",
    "created_at",
    "updated_at",
    "preco_liquido",
    "ri",
    "n_acomp",
    "eflag_e",
    "reqc",
    "data_rc",
    "tpdc",
    "requisitante",
    "criado_por_rc",
    "item",
    "tmatt",
    "grp_mercads",
    "empremp",
    "cen_cen",
    "dep_dep",
    "tipo_doc_compra",
    "doc_compra",
    "criado_por_pedido",
    "data_doc",
    "dt_remessa",
    "data_migo",
    "est_liber",
    "estr",
    "codigo_liberacao_doc_compra",
    "itm_liberacao",
    "criado_por_liberacao",
    "qtd_pedido",
    "por",
    "qtd_fornecida",
    "crf",
    "ump_1",
    "unidade_medida_pedido",
    "preco_liquido_unit",
    "moeda_1",
    "valor_em_brl",
    "moeda_2",
    "ump_2",
    "valor_liquido",
    "fornecedor_codigo",
    "cnpj_fornecedor",
    "fornecedor_nome",
    "req_cotacao",
    "data_pc_sc",
    "item_rc_cotacao",
    "upp",
    "valor_efetivo",
    "moeda_3",
    "doc_compra_ref",
    "itm_ref",
    "ftf",
    "posicao",
    "condicao_pagamento",
    "criado_por_condicao",
    "contrato",
    "item_contrato",
    "cn_lcr_parcs",
    "categoria",
    "grupo_mercadoria_curto",
    "ci",
    "unidade_medida_basica",
    "ump_3",
    "modificado_em"
   FROM "public"."sap_zl0132_po";


ALTER VIEW "public"."pedidosforn" OWNER TO "postgres";

GRANT ALL ON TABLE "public"."pedidosforn" TO "postgres", "anon", "authenticated", "service_role";

-- ----- requisicoes -----
CREATE OR REPLACE VIEW "public"."requisicoes" WITH ("security_invoker"='true') AS
 SELECT "ri",
    "tipo_de_documento",
    "requisicao_de_compra",
    "item_reqc",
    "data_da_solicitacao",
    "requisitante",
    "area_solicitante",
    "material",
    "texto_breve",
    "qtd_solicitada",
    "unidade_de_medida",
    "status_processamento",
    "codigo_de_eliminacao",
    "categoria_do_item",
    "ctg_class_cont",
    "tipo_data_de_remessa",
    "remessas_de_ate",
    "grupo_de_mercadorias",
    "centro",
    "deposito",
    "grupo_de_compradores",
    "n_acompanhamento",
    "fornecedor_fixo",
    "centro_fornecedor",
    "organiz_compras",
    "contrato_basico",
    "it_contrato_superior",
    "n_de_reqsc",
    "criado_por",
    "data_do_pedido",
    "moeda",
    "pedido",
    "item_do_pedido",
    "apelido",
    "aplicacao",
    "data_de_remessa",
    "codigo_de_bloqueio",
    "codigo_de_liberacao",
    "concluida",
    "data_da_liberacao",
    "data_pedido_origem",
    "descricao_do_grupo_de_compradores",
    "marca_da_peca",
    "modelo",
    "n_material_fornecedor",
    "n_peca_fabricante",
    "nome_do_fornecedor",
    "peca_original",
    "quantidade_pedida",
    "sugestao_local_compra",
    "tempo_procmto_em",
    "tipo_de_transporte",
    "requisicao_externa",
    "obs_comprador",
    "data_entrega_prevista",
    "presente_ultima_carga",
    "eliminado",
    "campos_extras",
    "obs_updated_at",
    "obs_updated_by",
    "item_status",
    "item_status_updated_at",
    "item_status_updated_by"
   FROM "public"."sap_me5a_rc";


ALTER VIEW "public"."requisicoes" OWNER TO "postgres";

GRANT ALL ON TABLE "public"."requisicoes" TO "postgres", "anon", "authenticated", "service_role";

-- ----- view_enriched_pedidos -----
CREATE OR REPLACE VIEW "public"."view_enriched_pedidos" WITH ("security_invoker"='true') AS
 SELECT "ri",
    "n_acomp",
    "eflag_e",
    "reqc",
    "data_rc",
    "tpdc",
    "requisitante",
    "criado_por_rc",
    "item",
    "material",
    "txt_breve",
    "tmatt",
    "grp_mercads",
    "empremp",
    "cen_cen",
    "dep_dep",
    "tipo_doc_compra",
    "doc_compra",
    "criado_por_pedido",
    "data_doc",
    "dt_remessa",
    "data_migo",
    "est_liber",
    "estr",
    "codigo_liberacao_doc_compra",
    "itm_liberacao",
    "criado_por_liberacao",
    "qtd_pedido",
    "por",
    "qtd_fornecida",
    "crf",
    "ump_1",
    "unidade_medida_pedido",
    "preco_liquido_unit",
    "moeda_1",
    "valor_em_brl",
    "moeda_2",
    "ump_2",
    "valor_liquido",
    "fornecedor_codigo",
    "cnpj_fornecedor",
    "fornecedor_nome",
    "regiao_uf",
    "req_cotacao",
    "data_pc_sc",
    "item_rc_cotacao",
    "upp",
    "valor_efetivo",
    "moeda_3",
    "doc_compra_ref",
    "itm_ref",
    "ftf",
    "posicao",
    "condicao_pagamento",
    "criado_por_condicao",
    "modificado_em",
    "contrato",
    "item_contrato",
    "cn_lcr_parcs",
    "categoria",
    "grupo_mercadoria_curto",
    "ci",
    "unidade_medida_basica",
    "ump_3",
    "campos_extras",
    "status_entrega",
    "dias_atrasado"
   FROM "public"."vw_sap_pedidos_enriquecidos";


ALTER VIEW "public"."view_enriched_pedidos" OWNER TO "postgres";

GRANT ALL ON TABLE "public"."view_enriched_pedidos" TO "postgres", "anon", "authenticated", "service_role";

-- ----- view_enriched_requisicoes -----
CREATE OR REPLACE VIEW "public"."view_enriched_requisicoes" WITH ("security_invoker"='true') AS
 SELECT "ri",
    "tipo_de_documento",
    "requisicao_de_compra",
    "item_reqc",
    "data_da_solicitacao",
    "requisitante",
    "area_solicitante",
    "material",
    "texto_breve",
    "qtd_solicitada",
    "unidade_de_medida",
    "status_processamento",
    "codigo_de_eliminacao",
    "categoria_do_item",
    "ctg_class_cont",
    "tipo_data_de_remessa",
    "remessas_de_ate",
    "grupo_de_mercadorias",
    "centro",
    "deposito",
    "grupo_de_compradores",
    "n_acompanhamento",
    "fornecedor_fixo",
    "centro_fornecedor",
    "organiz_compras",
    "contrato_basico",
    "it_contrato_superior",
    "n_de_reqsc",
    "criado_por",
    "data_do_pedido",
    "moeda",
    "pedido",
    "item_do_pedido",
    "apelido",
    "aplicacao",
    "data_de_remessa",
    "codigo_de_bloqueio",
    "codigo_de_liberacao",
    "concluida",
    "data_da_liberacao",
    "data_pedido_origem",
    "descricao_do_grupo_de_compradores",
    "marca_da_peca",
    "modelo",
    "n_material_fornecedor",
    "n_peca_fabricante",
    "nome_do_fornecedor",
    "peca_original",
    "quantidade_pedida",
    "sugestao_local_compra",
    "tempo_procmto_em",
    "tipo_de_transporte",
    "requisicao_externa",
    "obs_comprador",
    "data_entrega_prevista",
    "presente_ultima_carga",
    "eliminado",
    "campos_extras",
    "obs_updated_at",
    "obs_updated_by",
    "documento_compra",
    "item_pedido",
    "fornecedor_code",
    "fornecedor_name",
    "data_pedido",
    "data_migo",
    "data_entrega_sap",
    "status_entrega",
    "dias_atrasado",
    "natureza",
    "status_requisicao",
    "lead_time_compras_meta",
    "data_referencia_prazo",
    "atraso_comprador",
    "status_atualizado",
    "faixa_atraso",
    "alerta",
    "dias_em_aberto",
    "item_status",
    "item_status_updated_at",
    "item_status_updated_by",
    "criado_por_pedido"
   FROM "public"."vw_sap_requisicoes_enriquecidas";


ALTER VIEW "public"."view_enriched_requisicoes" OWNER TO "postgres";

GRANT ALL ON TABLE "public"."view_enriched_requisicoes" TO "postgres", "anon", "authenticated", "service_role";
