-- Script SQL de criação e alteração da tabela me3n_contratos no Supabase
-- Transação ME3N (Contratos)

-- 1. Se a tabela me3m_contratos existir e me3n_contratos ainda não existir, renomeia a tabela:
do $$
begin
  if exists (
    select 1 from information_schema.tables 
    where table_schema = 'public' and table_name = 'me3m_contratos'
  ) and not exists (
    select 1 from information_schema.tables 
    where table_schema = 'public' and table_name = 'me3n_contratos'
  ) then
    alter table public.me3m_contratos rename to me3n_contratos;
  end if;
end $$;

-- 2. Garante a criação da tabela me3n_contratos caso ainda não exista nenhuma das duas:
create table if not exists public.me3n_contratos (
  id bigint generated by default as identity primary key,
  documento_compras text not null,
  data_documento date,
  fornecedor text,
  centro text,
  item text,
  material text,
  texto_breve text,
  qtd_solicit_anterior numeric,
  unidade_preco text,
  preco_liquido numeric,
  valor_solicitado numeric,
  valor_efetivo numeric,
  qtd_prev_pendente numeric,
  valor_pendente numeric,
  a_fornecer_qtd numeric,
  a_fornecer_valor numeric,
  ainda_faturar_qtd numeric,
  ainda_faturar_valor numeric,
  fim_validade date,
  inicio_validade date,
  codigo_eliminacao text,
  um_pedido text,
  moeda text,
  estado_liberacao text,
  codigo_liberacao text,
  valor_liquido_pedido numeric,
  requisitante text,
  historico_pedido text,
  criado_por text,
  imported_at timestamp with time zone default now()
);

-- 3. Se a tabela me3n_contratos continha colunas de data no tipo 'text', altera para 'date':
do $$
begin
  if exists (
    select 1 from information_schema.columns 
    where table_schema = 'public' and table_name = 'me3n_contratos' and column_name = 'data_documento' and data_type = 'text'
  ) then
    alter table public.me3n_contratos alter column data_documento type date using data_documento::date;
  end if;

  if exists (
    select 1 from information_schema.columns 
    where table_schema = 'public' and table_name = 'me3n_contratos' and column_name = 'inicio_validade' and data_type = 'text'
  ) then
    alter table public.me3n_contratos alter column inicio_validade type date using inicio_validade::date;
  end if;

  if exists (
    select 1 from information_schema.columns 
    where table_schema = 'public' and table_name = 'me3n_contratos' and column_name = 'fim_validade' and data_type = 'text'
  ) then
    alter table public.me3n_contratos alter column fim_validade type date using fim_validade::date;
  end if;
end $$;

-- 4. Índices de busca e ordenação por data
create index if not exists idx_me3n_contratos_material on public.me3n_contratos(material);
create index if not exists idx_me3n_contratos_fornecedor on public.me3n_contratos(fornecedor);
create index if not exists idx_me3n_contratos_validade on public.me3n_contratos(inicio_validade, fim_validade);
