-- Script SQL de criação da tabela fbl1n_c_pagar no Supabase
-- Transação FBL1N (Contas a Pagar)

create table if not exists public.fbl1n_c_pagar (
  id bigint generated by default as identity primary key,
  simbolo_partida text,
  codigo_imposto text,
  empresa text not null,
  chave_referencia_1 text,
  conta text,
  numero_documento text not null,
  razao_social_fornecedor text,
  ano_mes text,
  referencia text,
  data_documento date,
  data_lancamento date,
  tipo_documento text,
  estorno_com text,
  conta_lancamento_contrapartida text,
  data_pagamento date,
  montante_moeda_doc numeric,
  montante_base_desconto numeric,
  montante_base_irf numeric,
  montante_irf numeric,
  moeda_documento text,
  data_compensacao date,
  doc_compensacao text,
  centro text,
  documento_compras text,
  elemento_pep text,
  imobilizado text,
  loc_negocios text,
  id_fiscal_1 text,
  id_fiscal_iva text,
  texto text,
  atribuicao text,
  centro_lucro text,
  parcelamento_tributario text,
  texto_cabecalho_documento text,
  bloqueio_pagamento text,
  montante_mi2 numeric,
  montante_mi3 numeric,
  condicoes_pagamento text,
  data_entrada date,
  doc_faturamento text,
  fornecedor text,
  motivo_estorno text,
  vencimento_liquido date,
  vencimento_original date,
  parcela text,
  campos_extras jsonb,
  imported_at timestamp with time zone default now()
);

create index if not exists idx_fbl1n_c_pagar_numero_documento on public.fbl1n_c_pagar(numero_documento);
create index if not exists idx_fbl1n_c_pagar_fornecedor on public.fbl1n_c_pagar(razao_social_fornecedor);
create index if not exists idx_fbl1n_c_pagar_empresa on public.fbl1n_c_pagar(empresa);
create index if not exists idx_fbl1n_c_pagar_vencimento on public.fbl1n_c_pagar(vencimento_liquido);
create index if not exists idx_fbl1n_c_pagar_doc_compensacao on public.fbl1n_c_pagar(doc_compensacao);
