/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Cópia das tabelas de domínio `public.impostos` (150 códigos) e `public.ddp`
 * (95 códigos) lidas diretamente do Supabase do projeto, para testar
 * matching.ts contra o catálogo real em vez de um exemplo inventado — a
 * lógica de sugerirImposto/sugerirDDP só é confiável se validada contra as
 * composições e inconsistências (Simples Nacional, FCI, "Fora Quinzena")
 * que o catálogo de verdade tem.
 */

import type { CodigoImposto, CodigoDDP } from '../matching';

export const CATALOGO_IMPOSTOS_REAL: CodigoImposto[] = [
  { incoterms: 'A0', descricao: 'Saída Industrialização: sem impostos' },
  { incoterms: 'A1', descricao: 'Saída Industrialização: ICMS' },
  { incoterms: 'A3', descricao: 'Saída Industrialização: ICMS + IPI' },
  { incoterms: 'B0', descricao: 'Saída Consumo: sem impostos' },
  { incoterms: 'B1', descricao: 'Saída Consumo: ICMS' },
  { incoterms: 'B3', descricao: 'Saída Consumo: ICMS + IPI' },
  { incoterms: 'C0', descricao: 'Entr.Consumo: sem impostos' },
  { incoterms: 'C1', descricao: 'Entr.Consumo: ICMS + DIFAL' },
  { incoterms: 'C2', descricao: 'Entr.Consumo: ICMS + ST' },
  { incoterms: 'C3', descricao: 'Entr.Consumo: ICMS + DIFAL + IPI' },
  { incoterms: 'C4', descricao: 'Entr.Consumo: ICMS + ST + IPI' },
  { incoterms: 'C5', descricao: 'Entr.Consumo: IPI' },
  { incoterms: 'C6', descricao: 'Entr.Consumo: ICMS Simples Nacional + DIFAL' },
  { incoterms: 'C7', descricao: 'Entr.Consumo: ICMS Simples Nacional + DIFAL + IPI' },
  { incoterms: 'C8', descricao: 'Entr.Consumo: ICMS s/ DIFAL' },
  { incoterms: 'C9', descricao: 'Entr.Consumo: ICMS retido por ST' },
  { incoterms: 'CA', descricao: 'Entr.Consumo: ICMS s/recup + IPI s/recup (s/ DIFAL)' },
  { incoterms: 'CB', descricao: 'Entr.Consumo: ICMS Simples Nacional + ST' },
  { incoterms: 'CC', descricao: 'Entr.Consumo: ICMS Simples Nacional + ST + IPI' },
  { incoterms: 'CE', descricao: 'Entr. Frete consumo: ICMS destac/DIFAL - CT-e Pad.' },
  { incoterms: 'CF', descricao: 'Entr. Frete consumo: ICMS destacado' },
  { incoterms: 'CG', descricao: 'Entr. Frete consumo: ICMS destacado - CT-e Pad.' },
  { incoterms: 'CH', descricao: 'Entr. Frete consumo: SEM Impostos - CT-e Pad.' },
  { incoterms: 'CM', descricao: 'Entr.Consumo: ICMS 4% s rec + IPI s/rec + DIFAL' },
  { incoterms: 'CN', descricao: 'Entr.Consumo: ICMS 4% (FCI) s recup + DIFAL' },
  { incoterms: 'CP', descricao: 'Entr.Consumo: ICMS 4% (FCI) s recup + ST' },
  { incoterms: 'CR', descricao: 'Entr.Consumo: ICMS 4% (FCI) s recup + ST + IPI s/rec' },
  { incoterms: 'CS', descricao: 'Entr.Consumo: ICMS 4% (FCI) s recup' },
  { incoterms: 'CT', descricao: 'Entr.Consumo: ICMS 4% (FCI) s recup + IPI s/recup' },
  { incoterms: 'D0', descricao: 'Entr.Ativo: sem impostos' },
  { incoterms: 'D1', descricao: 'Entr.Ativo: ICMS CIAP + DIFAL' },
  { incoterms: 'D2', descricao: 'Entr.Ativo: ICMS CIAP + DIFAL CIAP + IPI s/ recup' },
  { incoterms: 'F1', descricao: 'IV Future delivery Difal consumption & assets' },
  { incoterms: 'F2', descricao: 'Inp. Consumption: ICMS + CompICMS (DIFAL)' },
  { incoterms: 'G1', descricao: 'Fatura: EF DIFAL' },
  { incoterms: 'G2', descricao: 'GR Difal Investments' },
  { incoterms: 'H0', descricao: 'Entr.Consumo: sem impostos + PIS/COFINS' },
  { incoterms: 'H1', descricao: 'Entr.Consumo: ICMS + DIFAL + PIS/COFINS' },
  { incoterms: 'H2', descricao: 'Entr.Consumo: ICMS + ST + PIS/COFINS' },
  { incoterms: 'H3', descricao: 'Entr.Consumo: ICMS + DIFAL + IPI + PIS/COFINS' },
  { incoterms: 'H4', descricao: 'Entr.Consumo: ICMS + ST + IPI + PIS/COFINS' },
  { incoterms: 'H5', descricao: 'Entr.Consumo: IPI + PIS/COFINS' },
  { incoterms: 'H6', descricao: 'Entr.Consumo: ICMS Simpl Nac + DIFAL + PIS/COFINS' },
  { incoterms: 'H7', descricao: 'Entr.Consumo: ICMS Simpl Nac + DIFAL + IPI + PIS/COFINS' },
  { incoterms: 'H8', descricao: 'Entr.Consumo: ICMS s/ DIFAL + PIS/COFINS' },
  { incoterms: 'H9', descricao: 'Entr.Consumo: ICMS s/ DIFAL + IPI + PIS/COFINS' },
  { incoterms: 'HA', descricao: 'Serviço: Sem Impostos + PIS/COFINS crédito' },
  { incoterms: 'HB', descricao: 'Serviço: ISS + PIS/COFINS crédito' },
  { incoterms: 'HC', descricao: 'Serviço: ISS + PIS/COFINS/CSLL + PIS/COFINS crédito' },
  { incoterms: 'HD', descricao: 'Serviço: PIS/COFINS/CSLL + PIS/COFINS crédito' },
  { incoterms: 'HE', descricao: 'Entr. Futura. Fatura s/ impostos + PIS/COFINS (K1)' },
  { incoterms: 'HF', descricao: 'Entr. Fut. Fatura: ICMS s/ recup + PIS/COFINS (K6)' },
  { incoterms: 'HG', descricao: 'Entr. Fut. Fat: ICMS/IPI s/recup + PIS/COFINS (K3)' },
  { incoterms: 'HI', descricao: 'Entr. Fut. Fat: ICMS + ST s/recup + PIS/COFINS (KG)' },
  { incoterms: 'HJ', descricao: 'Entr. Fut. Fat: ICMS Simp.Nac. + DIF. + PIS/COFINS (KN)' },
  { incoterms: 'HK', descricao: 'Entr. Fut. Fat: ICMS s/recup + DIFAL + PIS/COFINS (KE)' },
  { incoterms: 'HL', descricao: 'Entr. Fut.Fat: ICMS/IPI s/recup + DIF. PIS/COFINS (KQ)' },
  { incoterms: 'HM', descricao: 'Entr.Consumo: ICMS 4% + DIFAL + PIS/COFINS' },
  { incoterms: 'HN', descricao: 'Entr.Consumo: ICMS 4% + DIFAL + IPI + PIS/COFINS' },
  { incoterms: 'HO', descricao: 'Entr.Consumo: ICMS 4% s/ DIFAL + PIS/COFINS' },
  { incoterms: 'HP', descricao: 'Entr.Consumo: ICMS 4% s/ DIFAL + IPI + PIS/COFINS' },
  { incoterms: 'I0', descricao: 'Entr. Industrialização: sem impostos + PIS/COFINS' },
  { incoterms: 'I1', descricao: 'Entr. Industrialização: ICMS + PIS/COFINS' },
  { incoterms: 'I2', descricao: 'Entr. Industrialização: ICMS + ST + PIS/COFINS' },
  { incoterms: 'I3', descricao: 'Entr. Industrialização: ICMS + IPI + PIS/COFINS' },
  { incoterms: 'I4', descricao: 'Entr. Industrialização: ICMS + ST + IPI + PIS/COFINS' },
  { incoterms: 'I5', descricao: 'Entr. Industrialização: IPI + PIS/COFINS' },
  { incoterms: 'I6', descricao: 'Entr. Revenda: ICMS + IPI Custo + PIS/COFINS' },
  { incoterms: 'I7', descricao: 'Entr. Revenda: ICMS + ST + IPI Custo + PIS/COFINS' },
  { incoterms: 'I8', descricao: 'Entr. Industrialização: ICMS s/recup + IPI s/recup' },
  { incoterms: 'I9', descricao: 'Serviço: Sem Impostos' },
  { incoterms: 'IA', descricao: 'Serviço: ISS' },
  { incoterms: 'IB', descricao: 'Serviço: ISS + PIS/COFINS/CSLL' },
  { incoterms: 'IC', descricao: 'Serviço: PIS/COFINS/CSLL' },
  { incoterms: 'ID', descricao: 'Entr. Indust: ICMS com recup + PIS/COFINS' },
  { incoterms: 'IE', descricao: 'Entr. Industrialização: operações isentas de impostos' },
  { incoterms: 'IF', descricao: 'INATIVO Serviço: ICMS com recup' },
  { incoterms: 'IG', descricao: 'INATIVO Serviço: ICMS sem recup' },
  { incoterms: 'IH', descricao: 'Entr. Revenda: IPI Custo + PIS/COFINS' },
  { incoterms: 'II', descricao: 'Entr. Revenda: ICMS + ST + PIS/COFINS' },
  { incoterms: 'IJ', descricao: 'Serviço: ICMS sem recup + PIS/COFINS' },
  { incoterms: 'IL', descricao: 'Entr. Indust: ICMS 4% rec + IPI c rec + PIS/COFINS' },
  { incoterms: 'IM', descricao: 'Entr. Industr: ICMS 4% (FCI) c recup + PIS/COFINS' },
  { incoterms: 'IN', descricao: 'Entr. Indust: Somente PIS/COFINS' },
  { incoterms: 'IP', descricao: 'Entr. Indust: ICMS sem recup + PIS/COFINS' },
  { incoterms: 'IQ', descricao: 'Entr. Revenda: Apenas DIFAL' },
  { incoterms: 'IR', descricao: 'Entr. Revenda: ICMS 4% (FCI) sem recup + PIS/COFINS' },
  { incoterms: 'IS', descricao: 'Entr. Revenda: ICMS 4% (FCI) sem rec + IPI + PIS/COFINS' },
  { incoterms: 'IT', descricao: 'Entr Fut Rev Fatura: ICMS s/rec + PIS/COFINS (K9)' },
  { incoterms: 'K0', descricao: 'Entrega Futura - Fatura sem impostos (K1)' },
  { incoterms: 'K1', descricao: 'Entrega Futura - Materiais sem impostos (K0)' },
  { incoterms: 'K2', descricao: 'Entrega Futura Fatura: ICMS + IPI s/ recup (K3)' },
  { incoterms: 'K3', descricao: 'Entrega Futura Materiais: ICMS + IPI s/ recup (K2)' },
  { incoterms: 'K5', descricao: 'Entrega Futura Fatura: ICMS s/ recup (K6)' },
  { incoterms: 'K6', descricao: 'Entrega Futura Materiais: ICMS s/ recup (K5)' },
  { incoterms: 'K8', descricao: 'Entrega Futura Fatura: ICMS c/ recup (K9)' },
  { incoterms: 'K9', descricao: 'Entrega Futura Materiais: ICMS c/ recup (K8)' },
  { incoterms: 'KA', descricao: 'Entr Futura - Fatura: ICMS + IPI com recup (KB)' },
  { incoterms: 'KB', descricao: 'Entr Futura - Materiais: ICMS + IPI com recup (KA)' },
  { incoterms: 'KC', descricao: 'Entrega Futura Materiais: ICMS s/ recup + ST (K5)' },
  { incoterms: 'KD', descricao: 'Entrega Futura Fatura: ICMS s/ recup + DIFAL (KD)' },
  { incoterms: 'KE', descricao: 'Entrega Futura Materiais: ICMS s/recup + DIFAL (KE)' },
  { incoterms: 'KF', descricao: 'Entrega Futura Fatura: ICMS + ST s/ recup (KG)' },
  { incoterms: 'KG', descricao: 'Entrega Futura Materiais: ICMS + ST s/ recup (KF)' },
  { incoterms: 'KH', descricao: 'Entrega Futura - Fatura sem impostos (KI)' },
  { incoterms: 'KI', descricao: 'Entrega Futura - Materiais (Apenas DIFAL) (KH)' },
  { incoterms: 'KJ', descricao: 'Entrega Futura Fatura: ICMS (FCI) + ST s/ rec (KG)' },
  { incoterms: 'KL', descricao: 'Entrega Futura Materiais: ICMS (FCI) + ST s/ rec (KF)' },
  { incoterms: 'KM', descricao: 'Ent. Fut. fatura: ICMS Simples Nac + DIFAL (KN)' },
  { incoterms: 'KN', descricao: 'Entr. Fut. mat: ICMS Simples Nac + DIFAL (KM)' },
  { incoterms: 'KP', descricao: 'Entr. Fut. fatura: ICMS/IPI s/ recup. + DIFAL (KQ)' },
  { incoterms: 'KQ', descricao: 'Entr. Fut. mat: ICMS/IPI s/ recup. + DIFAL (KP)' },
  { incoterms: 'KR', descricao: 'Ent. Futura Fatura IMO: ICMS s/ recup + DIFAL (KD)' },
  { incoterms: 'KS', descricao: 'Ent Futura IMO Materiais: ICMS s/recup + DIFAL (KE)' },
  { incoterms: 'KY', descricao: 'Entrega Futura Fatura: ICMS s/ recup + DIFAL (KD)' },
  { incoterms: 'KZ', descricao: 'Entrega Futura Materiais: ICMS s/recup + DIFAL (KE)' },
  { incoterms: 'L0', descricao: 'Saída: sem impostos' },
  { incoterms: 'LO', descricao: '(reservado)' },
  { incoterms: 'R0', descricao: 'REIDI: Materiais (Sem impostos)' },
  { incoterms: 'R1', descricao: 'REIDI: Materiais (ICMS/IPI s/ recup)' },
  { incoterms: 'R2', descricao: 'REIDI: Serviços (ISSQN)' },
  { incoterms: 'R3', descricao: 'REIDI: Serviço/Locação (sem impostos)' },
  { incoterms: 'R4', descricao: 'REIDI: Materiais (ICMS/ST/IPI s/ recup)' },
  { incoterms: 'R5', descricao: 'REIDI: Materiais (ICMS com recuperação)' },
  { incoterms: 'R6', descricao: 'REIDI: Materiais (ICMS + ST com recuperação)' },
  { incoterms: 'R7', descricao: 'REIDI: Materiais (ICMS s/ recup + DIFAL)' },
  { incoterms: 'R8', descricao: 'REIDI: Materiais (ICMS s/recup + DIFAL + IPI)' },
  { incoterms: 'R9', descricao: 'REIDI: Materiais (Apenas DIFAL)' },
  { incoterms: 'RA', descricao: 'REIDI: Materiais ICMS retido por ST' },
  { incoterms: 'RB', descricao: 'REIDI: ICMS 4% (FCI) s recup' },
  { incoterms: 'RC', descricao: 'REIDI: ICMS 4% (FCI) s recup + ST' },
  { incoterms: 'RD', descricao: 'REIDI: ICMS s/ DIFAL' },
  { incoterms: 'RE', descricao: 'REIDI: ICMS s/recup + ST s/ recup' },
  { incoterms: 'RF', descricao: 'REIDI: ICMS 4% (FCI) s recup + IPI s/recup' },
  { incoterms: 'RG', descricao: 'REIDI: Materiais (somente IPI s/ recup)' },
  { incoterms: 'RH', descricao: 'REIDI: ISS + CSLL' },
  { incoterms: 'RI', descricao: 'REIDI: Somente CSLL' },
  { incoterms: 'S0', descricao: 'Saída SD: Sem impostos' },
  { incoterms: 'SD', descricao: 'Saída SD' },
  { incoterms: 'SE', descricao: 'Saída SD: Operações isentas de impostos' },
  { incoterms: 'SI', descricao: 'Saída SD: ISS' },
  { incoterms: 'SZ', descricao: 'Saída SD: ICMS ZF' },
  { incoterms: 'Y2', descricao: 'Entr.Consumo: ICMS + ST' },
  { incoterms: 'Y4', descricao: 'Entr.Consumo: ICMS + ST + IPI' },
  { incoterms: 'YA', descricao: 'CBS1' },
  { incoterms: 'YB', descricao: 'IBS1' },
  { incoterms: 'YP', descricao: 'Entr.Consumo: ICMS 4% (FCI) s recup + ST' },
  { incoterms: 'ZD', descricao: 'Entr. Frete CTE Débito Posterior ICMS c/ recup' },
  { incoterms: 'ZE', descricao: 'Entr. Frete CTE Débito Posterior ICMS s/ recup' },
  { incoterms: 'ZF', descricao: 'Entr. Frete consumo: ICMS destacado - Aliq. Difer.' },
];

export const CATALOGO_DDP_REAL: CodigoDDP[] = [
  { ddp: '0', descricao: 'Pagamento imediato s/desconto' },
  { ddp: '1', descricao: 'Pagamento imediato s/desconto' },
  { ddp: '12', descricao: '10% em 30 dias / 90% em 60 dias (10º dia)' },
  { ddp: '120', descricao: 'Dentro de 120 dias s/desconto' },
  { ddp: '13', descricao: '50% em 30 dias / 50% em 60 dias (10º dia)' },
  { ddp: '14', descricao: '60% em 30 dias / 40% em 60 dias (10º dia)' },
  { ddp: '15', descricao: 'Dentro de 15 dias s/desconto' },
  { ddp: '150', descricao: 'Dentro de 150 dias s/desconto' },
  { ddp: '16', descricao: '20% -30d / 40% -60d / 40% -90d (10º dia)' },
  { ddp: '180', descricao: 'Dentro de 180 dias s/desconto' },
  { ddp: '2', descricao: '14 dias 2%, 30 líquido' },
  { ddp: '20', descricao: '30 dias Fora Quinzena' },
  { ddp: '21', descricao: 'Dia 16 no mês seguinte' },
  { ddp: '22', descricao: 'Dia 16 em dois meses' },
  { ddp: '23', descricao: 'Dia 16 em três meses' },
  { ddp: '24', descricao: 'Dia 16 em quatro meses' },
  { ddp: '25', descricao: 'Dia 16 em cinco meses' },
  { ddp: '26', descricao: 'Dia 16 em dois meses - 50%/50%' },
  { ddp: '27', descricao: 'Dia 16 - 1ª e 2ª de 33,33% e 3ª de 33,34%' },
  { ddp: '28', descricao: '25% cada em 4 prestações' },
  { ddp: '29', descricao: '20% cada em 5 prestações' },
  { ddp: '3', descricao: '14 dias 3%, 20/2%, 30 líquido' },
  { ddp: '30', descricao: 'Dentro de 30 dias s/desconto' },
  { ddp: '31', descricao: '30 dias Fora Quinzena' },
  { ddp: '32', descricao: 'Pgto 50% à vista / 50% 30 dias' },
  { ddp: '33', descricao: 'Pgto 30% à vista / 70% 30 dias' },
  { ddp: '4', descricao: 'Pagamento imediato s/desconto — data básica em fim do mês' },
  { ddp: '45', descricao: 'Dentro de 45 dias s/desconto' },
  { ddp: '5', descricao: 'Pagamento no 10º dia em 1 mês / após 10º dia em 2 meses' },
  { ddp: '55', descricao: 'Pagamento no 10º dia em 2 meses / no 10º dia em 3 meses' },
  { ddp: '6', descricao: 'Até fim do mês 4% desc / até 15 do mês seguinte 2% / até 15 em 2 meses s/desc' },
  { ddp: '60', descricao: 'Dentro de 60 dias s/desconto' },
  { ddp: '7', descricao: 'Escalonado por entrada de fatura (15/fim do mês; 2% desc; s/desc em 2 meses)' },
  { ddp: '75', descricao: 'Dentro de 75 dias s/desconto' },
  { ddp: '8', descricao: '14 dias 2% / 30 dias 1,5% / 45 dias s/desc (data básica 30 ou 15 do mês seguinte)' },
  { ddp: '80', descricao: '3 parcelas (30/60/90) sempre dia 10' },
  { ddp: '81', descricao: 'Pagamento no 10º dia no mês seguinte' },
  { ddp: '82', descricao: 'Pagamento no 10º dia em 2 meses' },
  { ddp: '83', descricao: 'Pagamento no 10º dia em 3 meses' },
  { ddp: '84', descricao: '2 parcelas (30/60) sempre dia 10' },
  { ddp: '85', descricao: '4 parcelas (30/60/90/120) s/ dia 10' },
  { ddp: '89', descricao: '3 parcelas (30/60/90) sempre dia 25' },
  { ddp: '9', descricao: '1ª parc. 30% / 2ª 40% / 3ª 30%' },
  { ddp: '90', descricao: 'Dentro de 90 dias s/desconto' },
  { ddp: '95', descricao: 'Pagamento no 10º dia em 3 meses / em 4 meses' },
  { ddp: 'Z010', descricao: 'Pagamento imediato s/desconto' },
  { ddp: 'Z012', descricao: 'Pagamento em 12 vezes' },
  { ddp: 'Z020', descricao: 'Dentro de 7 dias s/desconto' },
  { ddp: 'Z025', descricao: '25 dias Fora Semana' },
  { ddp: 'Z030', descricao: 'Dentro de 10 dias s/desconto' },
  { ddp: 'Z035', descricao: 'Dentro de 20 dias s/desconto' },
  { ddp: 'Z040', descricao: 'Dentro de 21 dias s/desconto' },
  { ddp: 'Z041', descricao: 'Dentro de 28 dias s/desconto' },
  { ddp: 'Z042', descricao: 'Dentro de 35 dias s/desconto' },
  { ddp: 'Z043', descricao: 'Dentro de 42 dias s/desconto' },
  { ddp: 'Z044', descricao: 'Pagamento em 28/35/42 dias' },
  { ddp: 'Z045', descricao: 'Dentro de 52 dias s/desconto' },
  { ddp: 'Z046', descricao: '50% em 28 dias / 50% em 42 dias' },
  { ddp: 'Z047', descricao: '50% em 28 dias / 50% em 52 dias' },
  { ddp: 'Z048', descricao: '50% em 30 dias / 50% em 45 dias' },
  { ddp: 'Z049', descricao: 'Dentro de 56 dias s/desconto' },
  { ddp: 'Z050', descricao: 'Pagamento em 30/60/90 dias' },
  { ddp: 'Z051', descricao: 'Pagamento em 30/45/60 dias' },
  { ddp: 'Z052', descricao: '50% em 28 dias / 50% em 56 dias' },
  { ddp: 'Z053', descricao: 'Dentro de 84 dias s/desconto' },
  { ddp: 'Z054', descricao: 'Pagamento em 28/56/84 dias' },
  { ddp: 'Z055', descricao: 'Pgto 40% à vista - 60% 10º dia próximo' },
  { ddp: 'Z056', descricao: '50% em 25 dias / 50% em 40 dias' },
  { ddp: 'Z057', descricao: 'Pagamento a 25 dias' },
  { ddp: 'Z058', descricao: 'Pagamento a 40 dias' },
  { ddp: 'Z059', descricao: 'Pagamento em 30/60/90/120/150' },
  { ddp: 'Z060', descricao: 'Pagamento em 28/45/56 dias' },
  { ddp: 'Z061', descricao: 'Pagamento em 30/60/90/120' },
  { ddp: 'Z062', descricao: 'Pagamento em 30/60' },
  { ddp: 'Z063', descricao: '1ª e 2ª - 33,330% / 3ª - 33,340%' },
  { ddp: 'Z064', descricao: 'Pagamento no 10º dia em 4 meses' },
  { ddp: 'Z065', descricao: 'Pagamento em 28/35 dias' },
  { ddp: 'Z066', descricao: 'NF dia 01-15 → pag fim do mês; NF dia 16-31 → pag dia 16 mês seguinte' },
  { ddp: 'Z067', descricao: 'NF dia 01-10 → pag 25 do mês; NF dia 11-31 → pag dia 25 mês seguinte' },
  { ddp: 'Z068', descricao: 'NF dia 01-10 → pag 25 mês seguinte; NF dia 11-31 → pag dia 25 + 2 meses' },
  { ddp: 'Z080', descricao: 'Pagamento 10%/10%/40%/30%/5%/5%' },
  { ddp: 'Z120', descricao: 'Pagamento no 10º dia em 4 meses / em 5 meses' },
  { ddp: 'Z150', descricao: 'Pagamento no 10º dia em 5 meses / em 6 meses' },
  { ddp: 'Z180', descricao: 'Pagamento no 10º dia em 6 meses / em 7 meses' },
  { ddp: 'ZCAR', descricao: 'Pagamento Cartão Crédito - 30 dias' },
  { ddp: 'ZCEF', descricao: 'Conforme Eventos de Fabricação' },
  { ddp: 'ZFIN', descricao: 'Financiamento - BNDES - 180 dias' },
  { ddp: 'ZR01', descricao: 'Pagamento 20%/70%/5%/5%' },
  { ddp: 'ZR02', descricao: 'Pagamento 20%/20%/15%/35%/5%/5%' },
  { ddp: 'ZR03', descricao: 'Pagamento 95% / 5%' },
  { ddp: 'ZR10', descricao: 'Pagamento 90% / 10%' },
  { ddp: 'ZR20', descricao: 'Pagamento 90% / 5% / 5%' },
  { ddp: 'ZR30', descricao: 'Pagamento 10%/20%/60%/5%/5%' },
  { ddp: 'ZR40', descricao: 'Pagamento 60%/30%/5%/5%' },
  { ddp: 'ZR50', descricao: 'Pagamento 15%/15%/30%/30%/5%/5%' },
  { ddp: 'ZR60', descricao: 'Pagamento 10%/10%/40%/30%/5%/5%' },
  { ddp: 'ZR70', descricao: 'Pagamento 30%/30%/30%/5%/5%' },
  { ddp: 'ZR80', descricao: 'Pagamento 10% / 20% / 70%' },
  { ddp: 'ZR90', descricao: 'Pagamento 30%/60%/5%/5%' },
  { ddp: 'ZVAL', descricao: 'Pagamento Vale Refeição - 90 dias' },
];
