import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ChevronRight, Download, FileSpreadsheet, Loader2, Pencil, Plus, Search } from 'lucide-react';
import type { Profile } from '../../types';
import Modal, { ModalBody, ModalFooter, ModalHeader } from '../../components/ui/Modal';
import { useToast } from '../../components/ui/Toast';
import TabelaComRolagemSuperior from '../../components/ui/TabelaComRolagemSuperior';
import * as api from '../../lib/rhPlanoTreinamentosApi';
import { exportarCronogramaTreinamentosExcel } from '../../lib/rhPlanoTreinamentosExport';
import { competenciasPadrao, criarCompetenciasCronograma } from '../../lib/rhPlanoTreinamentosViewModel';

interface Props { user: Profile; onNavigate: (path: string) => void; }
const dinheiro = (valor?: number | null) => Number(valor || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const rotuloCompetencia = (competencia: string, incluirAno = true) => new Date(`${competencia}T12:00:00`).toLocaleDateString('pt-BR', { month: 'short', ...(incluirAno ? { year: '2-digit' } : {}) });
const quantidadeDoItem = (item: api.CronogramaRh) => item.meses.reduce((soma, mes) => soma + Number(mes.quantidade || 0), 0);

export default function RhCronogramaTreinamentos({ user, onNavigate }: Props) {
  const toast = useToast();
  const [dados, setDados] = useState<Awaited<ReturnType<typeof api.carregarCronogramaTreinamentos>> | null>(null);
  const [busca, setBusca] = useState(''); const [ano, setAno] = useState('todos'); const [vinculo, setVinculo] = useState('todos');
  const [modo, setModo] = useState<'resumo' | 'planilha'>('resumo');
  const [edicao, setEdicao] = useState<(Omit<api.CronogramaRh, 'id'> & { id?: string }) | null>(null);
  const [detalhe, setDetalhe] = useState<api.CronogramaRh | null>(null); const [salvando, setSalvando] = useState(false); const [exportando, setExportando] = useState(false);
  const carregar = async () => { try { setDados(await api.carregarCronogramaTreinamentos()); } catch (e) { toast.error(e instanceof Error ? e.message : 'Não foi possível carregar o cronograma.'); } };
  useEffect(() => { void carregar(); }, []);
  const anos = useMemo(() => [...new Set(criarCompetenciasCronograma(dados?.itens || []).map(item => item.slice(0, 4)))].sort(), [dados]);
  const competencias = useMemo(() => competenciasPadrao(anos.length ? anos.map(Number) : [2026, 2027]), [anos]);
  const itens = useMemo(() => (dados?.itens || []).filter(item => {
    const texto = `${item.descricao} ${item.chave}`.toLocaleLowerCase('pt-BR');
    return (!busca || texto.includes(busca.toLocaleLowerCase('pt-BR')))
      && (ano === 'todos' || item.meses.some(mes => mes.competencia.startsWith(ano)))
      && (vinculo === 'todos' || (vinculo === 'vinculado' ? Boolean(item.treinamento_id) : !item.treinamento_id));
  }), [dados, busca, ano, vinculo]);
  const abrir = (item?: api.CronogramaRh) => setEdicao(item ? { ...item, meses: competencias.map(competencia => ({ competencia, quantidade: item.meses.find(mes => mes.competencia === competencia)?.quantidade || 0 })) } : { chave: '', treinamento_id: null, descricao: '', cotacao: 0, unidade_mes: 1, quantidade_total: 0, meses: competencias.map(competencia => ({ competencia, quantidade: 0 })) });
  const salvar = async () => {
    if (!edicao?.descricao) return toast.error('Informe a descrição do treinamento.');
    const chave = edicao.chave || `${edicao.descricao.normalize('NFD').replace(/\p{Diacritic}/gu, '').toUpperCase().replace(/[^A-Z0-9]+/g, ' ').trim()}|${edicao.cotacao}|${edicao.unidade_mes}`;
    try { setSalvando(true); await api.salvarCronogramaTreinamento({ ...edicao, chave, quantidade_total: quantidadeDoItem(edicao as api.CronogramaRh) }, user.id); toast.success('Cronograma salvo.'); setEdicao(null); await carregar(); }
    catch (e) { toast.error(e instanceof Error ? e.message : 'Não foi possível salvar.'); } finally { setSalvando(false); }
  };
  const totalPrevisto = itens.reduce((soma, item) => soma + quantidadeDoItem(item) * Number(item.cotacao || 0), 0);
  const exportar = async () => {
    try { setExportando(true); await exportarCronogramaTreinamentosExcel(itens, competencias); toast.success('Planilha do cronograma exportada.'); }
    catch (e) { toast.error(e instanceof Error ? e.message : 'Não foi possível exportar a planilha.'); } finally { setExportando(false); }
  };
  return <div className="mx-auto max-w-7xl space-y-5 pb-12">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><button type="button" onClick={() => onNavigate('/rh')} className="mb-2 inline-flex items-center gap-1 text-xs font-semibold text-slate-500 hover:text-emerald-700"><ArrowLeft className="h-3.5 w-3.5" /> RH</button><h1 className="text-2xl font-bold text-slate-900">Cronograma de Treinamentos</h1><p className="mt-1 text-sm text-slate-500">Planejamento mensal de quantidades e orçamento, vinculado ao cadastro de treinamentos.</p></div><div className="flex gap-2"><button type="button" onClick={() => void exportar()} disabled={!dados || exportando} className="inline-flex items-center gap-1 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700 disabled:opacity-50"><Download className="h-4 w-4" /> {exportando ? 'Exportando...' : 'Exportar Excel'}</button><button type="button" onClick={() => abrir()} className="inline-flex items-center gap-1 rounded-xl bg-emerald-600 px-3 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4" /> Novo item</button></div></header>
    {!dados ? <Carregando /> : <>
      <div className="grid gap-3 sm:grid-cols-3"><Kpi label="Itens filtrados" valor={itens.length} /><Kpi label="Unidades previstas" valor={itens.reduce((soma, item) => soma + quantidadeDoItem(item), 0)} cor="text-blue-600" /><Kpi label="Custo previsto" valor={dinheiro(totalPrevisto)} cor="text-violet-600" /></div>
      <section className="rounded-2xl border border-slate-200 bg-white p-3"><div className="grid gap-2 md:grid-cols-[minmax(240px,1fr)_160px_180px]"><div className="relative"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={busca} onChange={e => setBusca(e.target.value)} className="h-10 w-full rounded-xl border border-slate-200 bg-white pl-10 pr-3 text-sm" placeholder="Buscar treinamento ou chave" /></div><select value={ano} onChange={e => setAno(e.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="todos">Todos os anos</option>{anos.map(valor => <option key={valor}>{valor}</option>)}</select><select value={vinculo} onChange={e => setVinculo(e.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="todos">Todos os vínculos</option><option value="vinculado">Vinculados ao cadastro</option><option value="pendente">Sem vínculo no cadastro</option></select></div><div className="mt-3 flex justify-between border-t border-slate-100 pt-3"><p className="text-xs text-slate-500">Clique no item para abrir a distribuição mensal e os dados da cotação.</p><div className="inline-flex rounded-lg bg-slate-100 p-0.5"><button type="button" onClick={() => setModo('resumo')} className={`rounded-md px-2 py-1 text-xs font-bold ${modo === 'resumo' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500'}`}>Resumo</button><button type="button" onClick={() => setModo('planilha')} className={`rounded-md px-2 py-1 text-xs font-bold ${modo === 'planilha' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500'}`}>Planilha</button></div></div></section>
      {modo === 'resumo' ? <Resumo itens={itens} competencias={competencias} abrirDetalhe={setDetalhe} editar={abrir} /> : <Planilha itens={itens} competencias={competencias} abrirDetalhe={setDetalhe} editar={abrir} />}
    </>}
    {edicao && <Modal onClose={() => setEdicao(null)} maxWidth="max-w-5xl" ariaLabel="Editar cronograma"><ModalHeader onClose={() => setEdicao(null)}><h2 className="font-bold">Item do cronograma</h2></ModalHeader><ModalBody><div className="grid gap-3 sm:grid-cols-2"><Campo label="Descrição" value={edicao.descricao} onChange={descricao => setEdicao({ ...edicao, descricao })} /><div><label className="mb-1 block text-xs font-bold text-slate-500">Cadastro de treinamento</label><select value={edicao.treinamento_id || ''} onChange={e => { const treinamento = dados?.catalogo.find(item => item.id === e.target.value); setEdicao({ ...edicao, treinamento_id: e.target.value || null, descricao: treinamento?.nome || edicao.descricao }); }} className="h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"><option value="">Selecionar</option>{dados?.catalogo.map(item => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></div><Campo label="Cotação por unidade" type="number" value={String(edicao.cotacao)} onChange={valor => setEdicao({ ...edicao, cotacao: Number(valor) || 0 })} /><Campo label="Unidade/mês" type="number" value={String(edicao.unidade_mes)} onChange={valor => setEdicao({ ...edicao, unidade_mes: Number(valor) || 0 })} /></div><p className="mb-2 mt-5 text-xs font-bold uppercase text-slate-500">Quantidades por mês</p><div className="grid grid-cols-3 gap-2 sm:grid-cols-6">{competencias.map(competencia => <div key={competencia}><label className="mb-1 block text-[10px] font-bold uppercase text-slate-500">{rotuloCompetencia(competencia)}</label><input type="number" min="0" step="0.01" value={edicao.meses.find(mes => mes.competencia === competencia)?.quantidade || ''} onChange={e => setEdicao({ ...edicao, meses: edicao.meses.map(mes => mes.competencia === competencia ? { ...mes, quantidade: Number(e.target.value) || 0 } : mes) })} className="h-9 w-full rounded border border-slate-200 px-2 text-sm" /></div>)}</div><p className="mt-3 rounded-lg bg-slate-50 px-3 py-2 text-sm"><b>Total calculado:</b> {quantidadeDoItem(edicao as api.CronogramaRh)} · <b>Custo previsto:</b> {dinheiro(quantidadeDoItem(edicao as api.CronogramaRh) * edicao.cotacao)}</p></ModalBody><ModalFooter><button type="button" onClick={() => setEdicao(null)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold">Cancelar</button><button type="button" onClick={() => void salvar()} disabled={salvando} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">{salvando ? 'Salvando...' : 'Salvar'}</button></ModalFooter></Modal>}
    {detalhe && <Modal onClose={() => setDetalhe(null)} maxWidth="max-w-4xl" ariaLabel="Detalhes do cronograma"><ModalHeader onClose={() => setDetalhe(null)}><div><p className="text-xs font-bold uppercase text-slate-500">Cronograma de treinamento</p><h2 className="font-bold">{detalhe.descricao}</h2></div></ModalHeader><ModalBody><div className="grid gap-3 sm:grid-cols-3"><Info label="Vínculo" valor={detalhe.treinamento_id ? 'Cadastro de treinamento' : 'Pendente de vínculo'} /><Info label="Cotação" valor={dinheiro(detalhe.cotacao)} /><Info label="Total previsto" valor={dinheiro(quantidadeDoItem(detalhe) * detalhe.cotacao)} /></div><div className="mt-5 overflow-hidden rounded-xl border border-slate-200"><div className="bg-slate-50 px-4 py-3 text-sm font-bold">Distribuição por competência</div><div className="grid grid-cols-3 gap-px bg-slate-200 sm:grid-cols-6">{competencias.map(competencia => <div key={competencia} className="bg-white p-3"><p className="text-[10px] font-bold uppercase text-slate-500">{rotuloCompetencia(competencia)}</p><p className="mt-1 text-lg font-bold">{detalhe.meses.find(mes => mes.competencia === competencia)?.quantidade || '—'}</p></div>)}</div></div></ModalBody><ModalFooter><button type="button" onClick={() => { setDetalhe(null); abrir(detalhe); }} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Editar item</button></ModalFooter></Modal>}
  </div>;
}

function Resumo({ itens, competencias, abrirDetalhe, editar }: { itens: api.CronogramaRh[]; competencias: string[]; abrirDetalhe: (item: api.CronogramaRh) => void; editar: (item: api.CronogramaRh) => void }) { return <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{itens.map(item => { const mesesAtivos = item.meses.filter(mes => mes.quantidade > 0); return <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><button type="button" onClick={() => abrirDetalhe(item)} className="flex items-center gap-1 text-left text-sm font-bold text-slate-900 hover:text-emerald-700">{item.descricao}<ChevronRight className="h-4 w-4" /></button><p className="mt-1 text-xs text-slate-500">{item.treinamento_id ? 'Vinculado ao cadastro' : 'Pendente de vínculo'}</p></div><button type="button" onClick={() => editar(item)} className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-100" aria-label="Editar item"><Pencil className="h-4 w-4" /></button></div><div className="mt-4 grid grid-cols-2 gap-2"><Info label="Quantidade" valor={String(quantidadeDoItem(item))} /><Info label="Custo previsto" valor={dinheiro(quantidadeDoItem(item) * item.cotacao)} /></div><div className="mt-4 border-t border-slate-100 pt-3"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">Competências previstas</p><p className="mt-1 text-xs text-slate-600">{mesesAtivos.length ? mesesAtivos.map(mes => `${rotuloCompetencia(mes.competencia)}: ${mes.quantidade}`).join(' · ') : `Sem distribuição em ${competencias.length} competências`}</p></div></article>; })}{!itens.length && <Vazio />}</section>; }
function Planilha({ itens, competencias, abrirDetalhe, editar }: { itens: api.CronogramaRh[]; competencias: string[]; abrirDetalhe: (item: api.CronogramaRh) => void; editar: (item: api.CronogramaRh) => void }) { return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center gap-2 border-b border-slate-100 px-4 py-3"><FileSpreadsheet className="h-4 w-4 text-emerald-600" /><p className="text-sm font-bold">Visão de planilha do cronograma</p><span className="text-xs text-slate-500">{itens.length} linhas</span></div><TabelaComRolagemSuperior larguraMinima={1500} ariaLabel="tabela do cronograma"><table className="min-w-[1500px] w-full text-left text-xs"><thead className="sticky top-0 z-10 bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="sticky left-0 z-20 bg-slate-50 px-3 py-3">Treinamento</th><th className="px-3 py-3">Cotação</th><th className="px-3 py-3">Unid./mês</th><th className="px-3 py-3">Total</th><th className="px-3 py-3">Custo previsto</th>{competencias.map(competencia => <th key={competencia} className="px-2 py-3 text-center">{rotuloCompetencia(competencia)}</th>)}<th className="px-3 py-3" /></tr></thead><tbody className="divide-y divide-slate-100">{itens.map(item => <tr key={item.id} className="hover:bg-slate-50"><td className="sticky left-0 bg-white px-3 py-3 font-semibold"><button type="button" onClick={() => abrirDetalhe(item)} className="text-left hover:text-emerald-700">{item.descricao}</button></td><td className="px-3 py-3">{dinheiro(item.cotacao)}</td><td className="px-3 py-3">{item.unidade_mes}</td><td className="px-3 py-3">{quantidadeDoItem(item)}</td><td className="px-3 py-3">{dinheiro(quantidadeDoItem(item) * item.cotacao)}</td>{competencias.map(competencia => <td key={competencia} className="px-2 py-3 text-center">{item.meses.find(mes => mes.competencia === competencia)?.quantidade || ''}</td>)}<td className="px-3 py-3"><button type="button" onClick={() => editar(item)} className="rounded p-1.5 text-slate-500 hover:bg-slate-100" aria-label="Editar item"><Pencil className="h-4 w-4" /></button></td></tr>)}</tbody></table></TabelaComRolagemSuperior>{!itens.length && <Vazio />}</section>; }
function Campo({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (valor: string) => void; type?: string }) { return <div><label className="mb-1 block text-xs font-bold text-slate-500">{label}</label><input type={type} value={value} onChange={e => onChange(e.target.value)} className="h-10 w-full rounded-lg border border-slate-200 px-3 text-sm" /></div>; }
function Info({ label, valor }: { label: string; valor: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold text-slate-800">{valor}</p></div>; }
function Kpi({ label, valor, cor = 'text-slate-900' }: { label: string; valor: string | number; cor?: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-1 text-2xl font-bold ${cor}`}>{valor}</p></div>; }
function Carregando() { return <div className="flex justify-center py-20"><Loader2 className="animate-spin text-slate-400" /></div>; }
function Vazio() { return <p className="col-span-full p-8 text-center text-sm text-slate-500">Nenhum item encontrado com estes filtros.</p>; }
