import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { ArrowLeft, BarChart3, CalendarCheck, CircleAlert, Loader2, Target, TrendingUp, Users } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Profile } from '../../types';
import { useToast } from '../../components/ui/Toast';
import * as api from '../../lib/rhPlanoTreinamentosApi';
import { resumirIndicadoresTreinamentos } from '../../lib/rhPlanoTreinamentosViewModel';

interface Props { user: Profile; onNavigate: (path: string) => void; }
const cores = ['#059669', '#2563eb', '#f59e0b', '#e11d48', '#7c3aed'];
const dinheiro = (valor: number) => valor.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 });

export default function RhRelatorioTreinamentos({ onNavigate }: Props) {
  const toast = useToast();
  const [dados, setDados] = useState<Awaited<ReturnType<typeof api.carregarPlanoTreinamentos>> | null>(null);
  const [cronograma, setCronograma] = useState<Awaited<ReturnType<typeof api.carregarCronogramaTreinamentos>> | null>(null);
  const [ano, setAno] = useState('todos'); const [tipo, setTipo] = useState<'todos' | api.PlanoRh['tipo_informacao']>('todos');
  useEffect(() => { Promise.all([api.carregarPlanoTreinamentos(), api.carregarCronogramaTreinamentos()]).then(([plano, agenda]) => { setDados(plano); setCronograma(agenda); }).catch(e => toast.error(e instanceof Error ? e.message : 'Não foi possível carregar os indicadores.')); }, []);
  const anos = useMemo(() => [...new Set([...(dados?.planos || []).map(item => item.data_inicio.slice(0, 4)), ...(cronograma?.itens || []).flatMap(item => item.meses.map(mes => mes.competencia.slice(0, 4)))].filter(Boolean))].sort().reverse(), [dados, cronograma]);
  const cronogramasFiltrados = useMemo(() => {
    if (!cronograma || tipo === 'todos') return cronograma?.itens || [];
    const tiposPorTreinamento = new Map(cronograma.catalogo.map(item => [item.id, item.tipo_informacao]));
    return cronograma.itens.filter(item => tiposPorTreinamento.get(item.treinamento_id || '') === tipo);
  }, [cronograma, tipo]);
  const resumo = useMemo(() => resumirIndicadoresTreinamentos(dados?.planos || [], cronogramasFiltrados, { ano, tipo }), [dados, cronogramasFiltrados, ano, tipo]);
  const cumprimento = resumo.programados ? Math.round((resumo.realizados / resumo.programados) * 100) : 0;
  const ocupacao = resumo.capacidade ? Math.round((resumo.participacoes / resumo.capacidade) * 100) : 0;
  const atencao = resumo.planos.filter(item => item.status === 'atrasado' || item.status === 'reagendado').slice(0, 6);
  return <div className="mx-auto max-w-7xl space-y-5 pb-12">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><button type="button" onClick={() => onNavigate('/rh')} className="mb-2 inline-flex items-center gap-1 text-xs font-semibold text-slate-500 hover:text-emerald-700"><ArrowLeft className="h-3.5 w-3.5" /> RH</button><h1 className="text-2xl font-bold text-slate-900">Indicadores de Treinamentos</h1><p className="mt-1 text-sm text-slate-500">Painel de execução, capacidade e orçamento calculado a partir do plano, participantes e cronograma.</p></div><div className="flex gap-2"><select value={ano} onChange={e => setAno(e.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="todos">Todos os anos</option>{anos.map(valor => <option key={valor}>{valor}</option>)}</select><select value={tipo} onChange={e => setTipo(e.target.value as typeof tipo)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="todos">Interno e externo</option><option value="interno">Interno</option><option value="externo">Externo</option><option value="nao_informado">Não informado</option></select></div></header>
    {!dados || !cronograma ? <div className="flex justify-center py-20"><Loader2 className="animate-spin text-slate-400" /></div> : <>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi icone={<CalendarCheck />} titulo="Execução" valor={`${resumo.realizados} / ${resumo.programados}`} apoio={`${cumprimento}% dos eventos`} cor="text-emerald-600" /><Kpi icone={<Users />} titulo="Participações" valor={resumo.participacoes} apoio={`${ocupacao}% da capacidade planejada`} cor="text-blue-600" /><Kpi icone={<Target />} titulo="Orçamento previsto" valor={dinheiro(resumo.custoPrevisto)} apoio="Cronograma mensal" cor="text-violet-600" /><Kpi icone={<TrendingUp />} titulo="Custo realizado" valor={dinheiro(resumo.custoRealizado)} apoio={resumo.custoPrevisto ? `${Math.round((resumo.custoRealizado / resumo.custoPrevisto) * 100)}% do previsto` : 'Sem previsão no período'} cor="text-slate-900" /></section>
      <section className="grid gap-5 xl:grid-cols-[minmax(0,1.6fr)_minmax(300px,0.8fr)]"><Painel titulo="Eventos programados x realizados" subtitulo="Distribuição mensal do plano filtrado"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={resumo.porMes}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="mes" tickLine={false} axisLine={false} fontSize={11} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} fontSize={11} /><Tooltip cursor={{ fill: '#f8fafc' }} /><Legend /><Bar dataKey="programados" name="Programados" fill="#94a3b8" radius={[4, 4, 0, 0]} /><Bar dataKey="realizados" name="Realizados" fill="#059669" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></Painel><Painel titulo="Situação do plano" subtitulo="Eventos no período"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={resumo.porStatus.filter(item => item.quantidade)} dataKey="quantidade" nameKey="status" innerRadius={56} outerRadius={88} paddingAngle={3}>{resumo.porStatus.filter(item => item.quantidade).map((item, indice) => <Cell key={item.status} fill={cores[indice]} />)}</Pie><Tooltip /><Legend verticalAlign="bottom" height={32} /></PieChart></ResponsiveContainer></div></Painel></section>
      <section className="grid gap-5 xl:grid-cols-[minmax(0,1.6fr)_minmax(300px,0.8fr)]"><Painel titulo="Custo previsto e participações" subtitulo="Previsto pelo cronograma e adesão registrada"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={resumo.porMes}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="mes" tickLine={false} axisLine={false} fontSize={11} /><YAxis yAxisId="participacoes" allowDecimals={false} tickLine={false} axisLine={false} fontSize={11} /><YAxis yAxisId="custo" orientation="right" tickLine={false} axisLine={false} fontSize={11} tickFormatter={valor => `R$ ${Math.round(valor / 1000)}k`} /><Tooltip formatter={(valor, nome) => [nome === 'Custo previsto' ? dinheiro(Number(valor)) : valor, nome]} /><Legend /><Line yAxisId="participacoes" type="monotone" dataKey="participacoes" name="Participações" stroke="#2563eb" strokeWidth={2.5} dot={{ r: 3 }} /><Line yAxisId="custo" type="monotone" dataKey="custoPrevisto" name="Custo previsto" stroke="#7c3aed" strokeWidth={2.5} dot={{ r: 3 }} /></LineChart></ResponsiveContainer></div></Painel><section className="rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><div className="flex items-center gap-2"><CircleAlert className="h-4 w-4 text-amber-600" /><h2 className="font-bold text-slate-900">Atenção operacional</h2></div><p className="mt-1 text-xs text-slate-500">Eventos atrasados ou reagendados no filtro atual.</p></div><div className="divide-y divide-slate-100">{atencao.length ? atencao.map(item => <div key={item.id} className="flex items-center justify-between gap-3 px-5 py-3"><div><p className="text-sm font-semibold text-slate-800">{item.titulo}</p><p className="mt-0.5 text-xs text-slate-500">{item.codigo} · {new Date(`${item.data_inicio}T12:00:00`).toLocaleDateString('pt-BR')}</p></div><span className="rounded-full bg-amber-100 px-2 py-1 text-[10px] font-bold uppercase text-amber-800">{item.status}</span></div>) : <p className="px-5 py-8 text-sm text-slate-500">Nenhum evento com atraso ou reagendamento.</p>}</div></section></section>
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 px-5 py-4"><div><h2 className="font-bold text-slate-900">Leitura de acompanhamento</h2><p className="mt-1 text-xs text-slate-500">Indicadores de referência para a rotina do RH.</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">Filtro: {ano === 'todos' ? 'todos os anos' : ano} · {tipo === 'todos' ? 'interno e externo' : tipo}</span></div><div className="grid divide-y divide-slate-100 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><Leitura titulo="Cumprimento" valor={`${cumprimento}%`} texto={`${resumo.realizados} de ${resumo.programados} eventos foram realizados.`} /><Leitura titulo="Ocupação" valor={`${ocupacao}%`} texto={`${resumo.participacoes} participações para ${resumo.capacidade} vagas planejadas.`} /><Leitura titulo="Desvio orçamentário" valor={resumo.custoPrevisto ? dinheiro(resumo.custoRealizado - resumo.custoPrevisto) : '—'} texto={resumo.custoPrevisto ? 'Realizado menos orçamento previsto no cronograma.' : 'Cadastre a distribuição mensal para comparar custos.'} /></div></section>
    </>}
  </div>;
}

function Painel({ titulo, subtitulo, children }: { titulo: string; subtitulo: string; children: ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold text-slate-900">{titulo}</h2><p className="mt-1 text-xs text-slate-500">{subtitulo}</p><div className="mt-4">{children}</div></section>; }
function Kpi({ icone, titulo, valor, apoio, cor }: { icone: ReactNode; titulo: string; valor: string | number; apoio: string; cor: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4"><span className="text-slate-400">{icone}</span><p className="mt-3 text-[10px] font-bold uppercase tracking-wide text-slate-500">{titulo}</p><p className={`mt-1 text-2xl font-bold ${cor}`}>{valor}</p><p className="mt-1 text-xs text-slate-500">{apoio}</p></div>; }
function Leitura({ titulo, valor, texto }: { titulo: string; valor: string; texto: string }) { return <div className="p-5"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">{titulo}</p><p className="mt-1 text-2xl font-bold text-slate-900">{valor}</p><p className="mt-2 text-xs leading-5 text-slate-500">{texto}</p></div>; }
