-- ==============================================================================
-- Tabela: mb51_mov_estoque
-- Descrição: Movimentações de Estoque SAP MM-IM (Transação MB51)
-- ==============================================================================

-- 1. Criação da tabela
CREATE TABLE IF NOT EXISTS public.mb51_mov_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    centro TEXT,
    deposito TEXT,
    referencia TEXT,
    doc_material TEXT NOT NULL,
    pedido TEXT,
    item TEXT,
    material TEXT,
    texto_breve_material TEXT,
    qtd_um_registro NUMERIC,
    unid_medida_basica TEXT,
    montante_mi NUMERIC,
    moeda TEXT,
    texto_cabecalho_doc TEXT,
    data_lancamento DATE,
    tipo_movimento TEXT,
    hora_registro TEXT,
    um_registro TEXT,
    data_documento DATE,
    data_entrada DATE,
    fornecedor TEXT,
    razao_social_fornecedor TEXT,
    txt_tipo_movimento TEXT,
    nome_usuario TEXT,
    posicao_deposito TEXT,
    elemento_pep TEXT,
    imobilizado TEXT,
    chave_unica TEXT UNIQUE,
    campos_extras JSONB,
    imported_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Ativação de RLS (Row Level Security)
ALTER TABLE public.mb51_mov_estoque ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Acesso (RLS)
DROP POLICY IF EXISTS "mb51_mov_estoque_read" ON public.mb51_mov_estoque;
CREATE POLICY "mb51_mov_estoque_read" ON public.mb51_mov_estoque
    FOR SELECT TO authenticated, anon
    USING (true);

DROP POLICY IF EXISTS "mb51_mov_estoque_insert" ON public.mb51_mov_estoque;
CREATE POLICY "mb51_mov_estoque_insert" ON public.mb51_mov_estoque
    FOR INSERT TO authenticated, anon
    WITH CHECK (true);

DROP POLICY IF EXISTS "mb51_mov_estoque_update" ON public.mb51_mov_estoque;
CREATE POLICY "mb51_mov_estoque_update" ON public.mb51_mov_estoque
    FOR UPDATE TO authenticated, anon
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS "mb51_mov_estoque_delete" ON public.mb51_mov_estoque;
CREATE POLICY "mb51_mov_estoque_delete" ON public.mb51_mov_estoque
    FOR DELETE TO authenticated, anon
    USING (true);

-- 4. Índices de performance
CREATE INDEX IF NOT EXISTS idx_mb51_mov_doc_material ON public.mb51_mov_estoque(doc_material);
CREATE INDEX IF NOT EXISTS idx_mb51_mov_material ON public.mb51_mov_estoque(material);
CREATE INDEX IF NOT EXISTS idx_mb51_mov_tipo_movimento ON public.mb51_mov_estoque(tipo_movimento);
CREATE INDEX IF NOT EXISTS idx_mb51_mov_data_lancamento ON public.mb51_mov_estoque(data_lancamento);
CREATE INDEX IF NOT EXISTS idx_mb51_mov_deposito ON public.mb51_mov_estoque(deposito);
CREATE INDEX IF NOT EXISTS idx_mb51_mov_elemento_pep ON public.mb51_mov_estoque(elemento_pep);
CREATE INDEX IF NOT EXISTS idx_mb51_mov_chave_unica ON public.mb51_mov_estoque(chave_unica);
