-- ==============================================================================
-- Tabela: proj_bom_gwjaco
-- Descrição: Estrutura BOM (Bill of Materials) do Projeto GW_JACOBINA
-- ==============================================================================

-- 1. Criação da tabela
CREATE TABLE IF NOT EXISTS public.proj_bom_gwjaco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projeto TEXT NOT NULL DEFAULT 'GW_JACOBINA',
    level INTEGER,
    section TEXT,
    "group" TEXT,
    find_number TEXT,
    part_number TEXT,
    codigo_equivalente_qingdao TEXT,
    revision TEXT,
    description TEXT,
    descricao TEXT,
    quantity NUMERIC(12, 3),
    each_weight_kg NUMERIC(12, 3),
    total_weight_kg NUMERIC(12, 3),
    uom TEXT,
    source TEXT,
    delivery_at TEXT,
    kit_atlanta TEXT,
    cod_sap TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Ativação de RLS (Row Level Security)
ALTER TABLE public.proj_bom_gwjaco ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Acesso (RLS)
DROP POLICY IF EXISTS "proj_bom_gwjaco_read" ON public.proj_bom_gwjaco;
CREATE POLICY "proj_bom_gwjaco_read" ON public.proj_bom_gwjaco
    FOR SELECT TO authenticated, anon
    USING (true);

DROP POLICY IF EXISTS "proj_bom_gwjaco_insert" ON public.proj_bom_gwjaco;
CREATE POLICY "proj_bom_gwjaco_insert" ON public.proj_bom_gwjaco
    FOR INSERT TO authenticated, anon
    WITH CHECK (true);

DROP POLICY IF EXISTS "proj_bom_gwjaco_update" ON public.proj_bom_gwjaco;
CREATE POLICY "proj_bom_gwjaco_update" ON public.proj_bom_gwjaco
    FOR UPDATE TO authenticated, anon
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS "proj_bom_gwjaco_delete" ON public.proj_bom_gwjaco;
CREATE POLICY "proj_bom_gwjaco_delete" ON public.proj_bom_gwjaco
    FOR DELETE TO authenticated, anon
    USING (true);

-- 4. Índices de performance
CREATE INDEX IF NOT EXISTS idx_proj_bom_gwjaco_projeto ON public.proj_bom_gwjaco(projeto);
CREATE INDEX IF NOT EXISTS idx_proj_bom_gwjaco_section ON public.proj_bom_gwjaco(section);
CREATE INDEX IF NOT EXISTS idx_proj_bom_gwjaco_part_number ON public.proj_bom_gwjaco(part_number);
CREATE INDEX IF NOT EXISTS idx_proj_bom_gwjaco_cod_sap ON public.proj_bom_gwjaco(cod_sap);
CREATE INDEX IF NOT EXISTS idx_proj_bom_gwjaco_level ON public.proj_bom_gwjaco(level);

-- 5. Permissões
GRANT SELECT, INSERT, UPDATE, DELETE ON public.proj_bom_gwjaco TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
