-- Script SQL de criação da tabela sap_me2l_pedido no Supabase
-- Transação ME2L (Pedidos de Compra)
--
-- "Nº acompanhamento" NÃO é chave de linha, apesar do nome sugerir um
-- identificador único: no relatório real ela vem em branco na grande maioria
-- das linhas e só aparece preenchida (com o texto "ADMIN", não um número)
-- numa fração pequena. A planilha também não traz número de item de PO — por
-- isso a importação é por substituição total (delete + insert do arquivo
-- inteiro), não por upsert com chave.

create table if not exists public.sap_me2l_pedido (
  id bigint generated by default as identity primary key,
  organizacao_compras text,
  centro text,
  material text,
  texto_breve text,
  codigo_eliminacao text,
  deposito text,
  data_documento date,
  n_acompanhamento text,
  requisicao_compra text,
  documento_compras text not null,
  fornecedor text,
  requisitante text,
  criado_por text,
  qtd_pedido numeric,
  a_fornecer_qtd numeric,
  um_pedido text,
  valor_liquido_pedido numeric,
  moeda text,
  unidade_preco text,
  contrato_basico text,
  grupo_liberacao text,
  codigo_imposto text,
  codigo_liberacao text,
  grupo_mercadorias text,
  imported_at timestamp with time zone not null default now()
);

create index if not exists idx_sap_me2l_pedido_documento on public.sap_me2l_pedido(documento_compras);
create index if not exists idx_sap_me2l_pedido_material on public.sap_me2l_pedido(material);
create index if not exists idx_sap_me2l_pedido_fornecedor on public.sap_me2l_pedido(fornecedor);
create index if not exists idx_sap_me2l_pedido_data on public.sap_me2l_pedido(data_documento);
create index if not exists idx_sap_me2l_pedido_requisicao on public.sap_me2l_pedido(requisicao_compra);
