-- ==============================================================================
-- Tabela: sup_bahiasul_entregas
-- Descrição: Base de dados das entregas das compras - Transportadora Bahia Sul (CTe)
-- ==============================================================================

-- 1. Criação da tabela
CREATE TABLE IF NOT EXISTS public.sup_bahiasul_entregas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cto_documento TEXT,
    cto_filial TEXT,
    cto_serie TEXT,
    cto_numero TEXT NOT NULL,
    tpo_embarque TEXT,
    rmt_nome TEXT,
    rmt_cnpj TEXT,
    dst_nome TEXT,
    dst_cnpj TEXT,
    emissao DATE,
    referencia DATE,
    prz_contratado DATE,
    embarque DATE,
    prv_chegada DATE,
    chegada DATE,
    prv_entrega DATE,
    entrega DATE,
    situacao TEXT,
    org_cidade TEXT,
    dst_cidade TEXT,
    nfs_embarcadas TEXT,
    kgs_declarado NUMERIC(12, 3),
    kgs_real NUMERIC(12, 3),
    kgs_cubado NUMERIC(12, 3),
    qtd_volumes INTEGER,
    vlr_mercadoria NUMERIC(15, 2),
    frt_cobrado NUMERIC(15, 2),
    obs_diversos TEXT,
    nro_pedido TEXT,
    chave_unica TEXT UNIQUE NOT NULL,
    imported_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Ativação de RLS (Row Level Security)
ALTER TABLE public.sup_bahiasul_entregas ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Acesso (RLS)
DROP POLICY IF EXISTS "sup_bahiasul_entregas_read" ON public.sup_bahiasul_entregas;
CREATE POLICY "sup_bahiasul_entregas_read" ON public.sup_bahiasul_entregas
    FOR SELECT TO authenticated, anon
    USING (true);

DROP POLICY IF EXISTS "sup_bahiasul_entregas_insert" ON public.sup_bahiasul_entregas;
CREATE POLICY "sup_bahiasul_entregas_insert" ON public.sup_bahiasul_entregas
    FOR INSERT TO authenticated, anon
    WITH CHECK (true);

DROP POLICY IF EXISTS "sup_bahiasul_entregas_update" ON public.sup_bahiasul_entregas;
CREATE POLICY "sup_bahiasul_entregas_update" ON public.sup_bahiasul_entregas
    FOR UPDATE TO authenticated, anon
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS "sup_bahiasul_entregas_delete" ON public.sup_bahiasul_entregas;
CREATE POLICY "sup_bahiasul_entregas_delete" ON public.sup_bahiasul_entregas
    FOR DELETE TO authenticated, anon
    USING (true);

-- 4. Índices de performance
CREATE INDEX IF NOT EXISTS idx_sup_bahiasul_nro_pedido ON public.sup_bahiasul_entregas(nro_pedido);
CREATE INDEX IF NOT EXISTS idx_sup_bahiasul_nfs_embarcadas ON public.sup_bahiasul_entregas(nfs_embarcadas);
CREATE INDEX IF NOT EXISTS idx_sup_bahiasul_cto_numero ON public.sup_bahiasul_entregas(cto_numero);
CREATE INDEX IF NOT EXISTS idx_sup_bahiasul_situacao ON public.sup_bahiasul_entregas(situacao);
CREATE INDEX IF NOT EXISTS idx_sup_bahiasul_emissao ON public.sup_bahiasul_entregas(emissao);
CREATE INDEX IF NOT EXISTS idx_sup_bahiasul_chave_unica ON public.sup_bahiasul_entregas(chave_unica);

-- 5. Permissões
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sup_bahiasul_entregas TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
