-- ==============================================================================
-- Tabela: tipo_mov_estoque
-- Descrição: Tipos de Movimento de Estoque (SAP MM-IM)
-- ==============================================================================

-- 1. Criação da tabela
CREATE TABLE IF NOT EXISTS public.tipo_mov_estoque (
    tmv VARCHAR(10) PRIMARY KEY,
    descricao TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Ativação de RLS (Row Level Security)
ALTER TABLE public.tipo_mov_estoque ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Acesso (RLS)
DROP POLICY IF EXISTS "tipo_mov_estoque_read" ON public.tipo_mov_estoque;
CREATE POLICY "tipo_mov_estoque_read" ON public.tipo_mov_estoque
    FOR SELECT TO authenticated, anon
    USING (true);

-- 4. Inserção / Atualização dos dados de tipo de movimento
INSERT INTO public.tipo_mov_estoque (tmv, descricao)
VALUES
    ('101', 'EM Entrada mercador.'),
    ('102', 'EM p/pedido estorno'),
    ('103', 'EM em estoque bloq.'),
    ('104', 'EM em EstBlq.estorno'),
    ('105', 'EM de estoque bloq.'),
    ('106', 'EM EstqBloq.estorno'),
    ('107', 'EM no estq.blq.aval.'),
    ('108', 'EM em EstBlqAvalEst.'),
    ('109', 'EM do estq.blq.aval.'),
    ('110', 'EM EstqBloqAval.est.'),
    ('121', 'EM compensação post.'),
    ('122', 'DM devolução fornec.'),
    ('123', 'DM dev.forn.estorno'),
    ('124', 'EM devol.estoq.bloq.'),
    ('125', 'EM dev.estq.blq.est.'),
    ('131', 'Entrada mercadorias'),
    ('132', 'Entrada mercadorias'),
    ('141', 'EM compens.post.mrc.'),
    ('142', 'EM compens.post.mrc.'),
    ('161', 'EM devolução'),
    ('162', 'EM estorno devolução'),
    ('201', 'SM para centro custo'),
    ('202', 'DM para centro custo'),
    ('221', 'SM para projeto'),
    ('222', 'DM para projeto'),
    ('231', 'SM p/ordem cliente'),
    ('232', 'DM p/ordem cliente'),
    ('241', 'SM para imobilizado'),
    ('242', 'DM para imobilizado'),
    ('251', 'SM para vendas'),
    ('252', 'DM para vendas'),
    ('261', 'SM para ordem'),
    ('262', 'DM para ordem'),
    ('281', 'SM para diagr.rede'),
    ('282', 'SM para diagr.rede'),
    ('291', 'SM todas as ClCont'),
    ('292', 'DM todas as ClCont'),
    ('301', 'TR transf.cent->cent'),
    ('302', 'ET transf.cent->cent'),
    ('303', 'TR Retir.dpst.->cent'),
    ('304', 'ET ret.do dep.p/cen.'),
    ('305', 'TR armazenar no cent'),
    ('306', 'ET armazenar no cen.'),
    ('309', 'TR Retif.mat.p/mat.'),
    ('310', 'ET transf.mat.p/mat.'),
    ('311', 'TR transf.no centro'),
    ('312', 'ET transf.no centro'),
    ('313', 'TR retir.dpst.->dpst'),
    ('314', 'ET retir.dpst.->dpst'),
    ('315', 'TR armazenar no dpst'),
    ('316', 'ET armazenar no dpst'),
    ('317', 'Agrup.mat.estrut.'),
    ('318', 'DM agrup.mat.estrut.'),
    ('319', 'Divisão mat.estrut.'),
    ('320', 'DM div.mat.estrut.'),
    ('321', 'TR qualidade->livre'),
    ('322', 'ET qualidade->livre'),
    ('323', 'TR qualidade no cent'),
    ('324', 'ET qualidade no cent'),
    ('325', 'TR bloqueado no cent'),
    ('326', 'ET bloqueado no cent'),
    ('331', 'SM para amostra Q.'),
    ('332', 'DM para amostra Q.'),
    ('333', 'SM para amostra L.'),
    ('334', 'DM para amostra L.'),
    ('335', 'SM -> amostra bloq.'),
    ('336', 'DM -> amostra bloq.'),
    ('340', 'Reavaliação Lotes'),
    ('341', 'TR livre -> não livr'),
    ('342', 'TR não livre-> livre'),
    ('343', 'TR bloqueado->livre'),
    ('344', 'ET bloqueado->livre'),
    ('349', 'TR bloqueado -> qld.'),
    ('350', 'ET bloqueado -> qld.'),
    ('351', 'TR p/estoq.trânsito'),
    ('352', 'ET p/estoq.trânsito'),
    ('411', 'TR depósito->depós.'),
    ('412', 'ET dep.->dep.'),
    ('413', 'TR dep.->ordem cli.'),
    ('414', 'ET dep.->ord.cli.'),
    ('415', 'TR depósito ->proj.'),
    ('416', 'ET dep.->proj.'),
    ('441', 'TP liv.->vasilh.ass.'),
    ('442', 'TP vasilh.ass.->liv.'),
    ('451', 'SM devoluções'),
    ('452', 'SM devoluç.Estorno'),
    ('453', 'TP devoluções->própr'),
    ('454', 'TP próprio->devoluç.'),
    ('455', 'TR transf.devoluções'),
    ('456', 'ET transf.devoluções'),
    ('457', 'TP dev.->próp.ctrl.q'),
    ('458', 'TP próp.ctrl.q.->dev'),
    ('459', 'TP def.-> próp.bloq.'),
    ('460', 'TP próp.bloq.-> dev.'),
    ('501', 'Entrada sem pedido'),
    ('502', 'DM entrada s/pedido'),
    ('503', 'Entrada no CtrQld.'),
    ('504', 'DM entrada no CtrQld'),
    ('505', 'Entrada estq.bloq.'),
    ('506', 'DM entrada bloquead.'),
    ('511', 'Remessa gratuita'),
    ('512', 'DM remessa gratuita'),
    ('521', 'Entrada s/OrdProd'),
    ('522', 'DM entrada s/OrdProd'),
    ('523', 'Entr.qual.s/OrdProd'),
    ('524', 'DM qualid.s/OrdProd'),
    ('525', 'Entr.bloq.sem OrdPr.'),
    ('526', 'DM bloq.s/OrdProd'),
    ('531', 'Entrada co-produto'),
    ('532', 'DM co-produto'),
    ('541', 'SM dpst.->remessa SC'),
    ('542', 'DM estq.SC->depósito'),
    ('543', 'SM Sc MDC'),
    ('544', 'EM Sc MDC'),
    ('545', 'Entrada Sc MDC'),
    ('546', 'SM subproduto Sc'),
    ('551', 'SM sucata'),
    ('552', 'DM sucata'),
    ('553', 'SM sucata Q.'),
    ('554', 'DM sucata Q.'),
    ('555', 'SM sucata bloq.'),
    ('556', 'DM sucata bloq.'),
    ('557', 'SM correção trânsito'),
    ('558', 'SM correção trânsito'),
    ('561', 'Reg.inic.estq.sist.'),
    ('562', 'DM reg.inic.estoque'),
    ('563', 'RegInicEstq.qualid.'),
    ('564', 'DM RegInicEstq Qual.'),
    ('565', 'RegInicEstq.bloq.'),
    ('566', 'DM RegInicEstq bloq.'),
    ('571', 'Entrada montagem'),
    ('572', 'DM entrada montagem'),
    ('573', 'Entr.montagem qual.'),
    ('574', 'DM entr.montagem q.'),
    ('575', 'Entr.bloq.montagem'),
    ('576', 'DM entr.bloq.montag.'),
    ('581', 'Entr.co-pr.diag.rede'),
    ('582', 'DM co-prod.diag.rede'),
    ('601', 'RM remessa mercador.'),
    ('602', 'DM rem.merc.estorno'),
    ('603', 'TR Retir.dpst.->cent'),
    ('604', 'ET ret.do dep.p/cen.'),
    ('605', 'TR armazenar no cent'),
    ('606', 'ET armazenar no cen.'),
    ('617', 'Agrp.est.mat.consig.'),
    ('618', 'Vl.agrp.est.mat.con.'),
    ('619', 'Div.estrn.mat.consig'),
    ('620', 'DM DivEstornMatConsg'),
    ('621', 'SM EmbRet emprestado'),
    ('622', 'SM EmbRet devolução'),
    ('623', 'SM saída EmbRet cli.'),
    ('624', 'SM entr.EmbRet clie.'),
    ('631', 'SM consig.emprestado'),
    ('632', 'SM consig.devolução'),
    ('633', 'SM saída consg.clie.'),
    ('634', 'SM entr.consig.clie.'),
    ('635', 'TR consig.emprestado'),
    ('636', 'ET consig.devolução'),
    ('641', 'TR p/estoq.trânsito'),
    ('642', 'ET p/estoq.trânsito'),
    ('643', 'TF to cross company'),
    ('644', 'TR to cross company'),
    ('645', 'TR interempresarial'),
    ('646', 'TD Cross Company'),
    ('647', 'TR p/estoq.trânsito'),
    ('648', 'ET p/estoq.trânsito'),
    ('651', 'RM DevolMerc devol.'),
    ('652', 'DM dev.merc.estorno'),
    ('653', 'FM devoluç.livre ut.'),
    ('654', 'FM devol.liv.ut.est.'),
    ('655', 'FM devoluç.qual.'),
    ('656', 'FM devoluç.qual.est.'),
    ('657', 'FM devoluç.bloq.'),
    ('658', 'FM devoluç.bloq.est.'),
    ('661', 'SM devol.ao fornec.'),
    ('662', 'DM estor.devol.forn.'),
    ('671', 'ET p/estoq.trânsito'),
    ('672', 'TR p/estoq.trânsito'),
    ('673', 'TF to cross company'),
    ('674', 'TR to cross company'),
    ('675', 'ET interempresarial'),
    ('676', 'TR interempresarial'),
    ('677', 'ET p/estoq.trânsito'),
    ('678', 'TR p/estoq.trânsito'),
    ('6A1', 'TR SM1'),
    ('6A2', 'ET SM1'),
    ('6A3', 'TR IE SM1'),
    ('6A4', 'ET IE SM1'),
    ('6A5', 'TR IE SM1'),
    ('6A6', 'ET IE SM1'),
    ('6A7', 'TR SM1'),
    ('6A8', 'ET SM1'),
    ('6AA', 'ET SM1'),
    ('6AB', 'TR SM1'),
    ('6AC', 'ET IE SM1'),
    ('6AD', 'TR IE SM1'),
    ('6AE', 'ET SM1'),
    ('6AF', 'TR SM1'),
    ('6AG', 'ET IE SM1'),
    ('6AH', 'TR IE SM1'),
    ('6B1', 'TR SM2'),
    ('6B2', 'ET SM2'),
    ('6B3', 'TR IE SM2'),
    ('6B4', 'ET IE SM2'),
    ('6B5', 'TR IE SM2'),
    ('6B6', 'ET IE SM2'),
    ('6B7', 'TR SM2'),
    ('6B8', 'ET SM2'),
    ('6BA', 'ET SM2'),
    ('6BB', 'TR SM2'),
    ('6BC', 'ET IE SM2'),
    ('6BD', 'TR IE SM2'),
    ('6K5', 'TR SM2 Consignação'),
    ('6K6', 'ET SM2 Consignação'),
    ('6W5', 'TR SM1 Consignação'),
    ('6W6', 'ET SM1 Consignação'),
    ('701', 'EM inventário depós.'),
    ('702', 'SM inventário dpst.'),
    ('703', 'EM inventário CtrQld'),
    ('704', 'SM inventário CtrQld'),
    ('707', 'EM inventário bloq.'),
    ('708', 'SM inventário bloq.'),
    ('711', 'SM DifInv depósito'),
    ('712', 'EM DifInv depósito'),
    ('713', 'SM DifInv CntrQld'),
    ('714', 'EM DifInv CntrQld'),
    ('715', 'SM DifInv devolução'),
    ('716', 'EM DifInv devolução'),
    ('717', 'SM DifInv bloq.'),
    ('718', 'EM DifInv bloq.'),
    ('721', 'Val.vnd.ent.s/ef.mrg'),
    ('722', 'Vl.vnd.saíd.s/ef.mrg'),
    ('731', 'Val.vnd.ent.c/ef.mrg'),
    ('732', 'Vl.vnd.saíd.c/ef.mrg'),
    ('801', 'EM c/fat.antec.+imp.'),
    ('802', 'EEM c/fat.ant.+imp'),
    ('803', 'EM fat.an.ICMS/IPI'),
    ('804', 'EEM fat.an.ICMS/IPI'),
    ('805', 'EM ft.ant.EsBlo.imp'),
    ('806', 'EEM FatAnEsBlo.c/imp'),
    ('811', 'EM EntrDir.c/imposto'),
    ('812', 'EEM EntrDir.c/imp'),
    ('815', 'EM EsBloEntrDi.c/im'),
    ('816', 'EEM EsBloEntDi.c/imp'),
    ('821', 'EM EsForn.aval.c/imp'),
    ('822', 'EEM EsFornAval.c/imp'),
    ('825', 'EM EsBlEsForAv.c/imp'),
    ('826', 'EEM EsBlEsForAvc/imp'),
    ('833', 'Transf.SM c/impost'),
    ('834', 'ETransf.SM c/impost'),
    ('835', 'Transf.EM c/impost'),
    ('836', 'ETransf.EM c/impost'),
    ('837', 'BR: Retorno com NF'),
    ('838', 'BR: estorn.837'),
    ('841', 'EMEqRT'),
    ('842', 'EEMEqRT'),
    ('843', 'EM EqRT c/impost'),
    ('844', 'EEM EqRT c/impost'),
    ('861', 'GR TFSD/MM'),
    ('862', 'GI TF SD/MM'),
    ('863', 'GI TF SD/MM Return'),
    ('864', 'GR TF SD/MM Return'),
    ('871', NULL),
    ('872', NULL),
    ('888', 'Entrada sem pedido'),
    ('889', 'DM entrada s/pedido'),
    ('901', 'Entrada material CAP'),
    ('902', 'Estorno entrada CAP'),
    ('921', 'SM para projeto'),
    ('922', 'DM para projeto'),
    ('930', 'DM entrada terceiros'),
    ('931', 'Ent Mat Terc. -Locaç'),
    ('932', 'DM entrada terceiros'),
    ('933', NULL),
    ('934', 'Mat Terc.- Rem.Ativo'),
    ('935', 'Mat Terc.- Indust.'),
    ('936', 'Mat Terc.- UnidIsent'),
    ('937', 'Mat Terc.-Ind X.901'),
    ('938', 'Mat Terc.- Conserto'),
    ('941', 'Envio mat Terceiros'),
    ('942', 'Est Envio Mat Terc'),
    ('951', 'EM Mat FATDI'),
    ('952', 'Est EM Mat FATDI'),
    ('953', 'EM Mat FATDI EAA'),
    ('955', 'SM Doação/Análise'),
    ('971', NULL),
    ('972', NULL),
    ('973', NULL),
    ('974', NULL),
    ('981', 'SM dpst.->remessa SC'),
    ('982', 'DM estq.SC->depósito'),
    ('991', 'EM c/fat.antec.+imp.'),
    ('992', 'EEM c/fat.ant.+imp'),
    ('Z21', NULL)
ON CONFLICT (tmv) DO UPDATE SET
    descricao = EXCLUDED.descricao,
    updated_at = NOW();
