-- Script SQL de criação da tabela zl0170_miro no Supabase
-- Relatório SAP ZL0170: reconciliação Pedido de Compra x MIGO (recebimento)
-- x MIRO (fatura/nota fiscal), usado para saber a qual PO uma fatura se refere.

create table if not exists public.zl0170_miro (
  id bigint generated by default as identity primary key,
  numero_pedido text not null,
  empresa text,
  centro text,
  data_criacao_pedido date,
  data_aprovacao_pedido date,
  data_remessa date,
  item text not null,
  material text,
  qtd_pedido numeric,
  unidade_pedido text,
  preco_liquido numeric,
  moeda_preco text,
  valor_liquido numeric,
  moeda_valor_liquido text,
  requisicao_compra text,
  data_solicitacao date,
  doc_migo text,
  ano_migo text,
  folha_servico text,
  data_criacao_migo date,
  data_lancamento_migo date,
  qtd_migo numeric,
  unidade_migo text,
  montante_migo numeric,
  moeda_migo text,
  doc_miro text,
  ano_miro text,
  data_criacao_miro date,
  data_lancamento_miro date,
  data_documento date,
  hora text,
  data_entrada date,
  referencia text,
  qtd_miro numeric,
  unidade_miro text,
  montante_miro numeric,
  numero_doc_contabil text,
  fornecedor text,
  nome_1 text,
  nome_2 text,
  id_fiscal_1 text,
  id_fiscal_2 text,
  id_fiscal_iva text,
  doc_pagamento text,
  data_pagamento date,
  campos_extras jsonb,
  imported_at timestamp with time zone default now()
);

create index if not exists idx_zl0170_miro_numero_pedido on public.zl0170_miro(numero_pedido);
create index if not exists idx_zl0170_miro_doc_miro on public.zl0170_miro(doc_miro);
create index if not exists idx_zl0170_miro_fornecedor on public.zl0170_miro(fornecedor);
create index if not exists idx_zl0170_miro_material on public.zl0170_miro(material);
create index if not exists idx_zl0170_miro_numero_doc_contabil on public.zl0170_miro(numero_doc_contabil);

alter table public.zl0170_miro enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'zl0170_miro' and policyname = 'zl0170_miro_all'
  ) then
    create policy zl0170_miro_all on public.zl0170_miro
      for all to authenticated using (true) with check (true);
  end if;
end $$;
