-- ZL0136: notas fiscais e valores tributários do SAP.
-- Cada importação substitui a fotografia anterior do relatório.

create table if not exists public.sap_zl0136_nf (
  id bigint generated by default as identity primary key,
  tipo_parceiro text,
  descricao_tipo_parceiro text,
  id_parceiro text,
  descricao_parceiro text,
  cnpj_parceiro text,
  numero_documento_nove_posicoes text not null,
  series text,
  categoria_nota_fiscal text,
  data_lancamento date,
  data_documento date,
  criado_por text,
  criado_manualmente text,
  modelo_nota_fiscal text,
  chave_acesso text,
  documento_faturamento text,
  tipo_documento_faturamento text,
  denominacao text,
  moeda_documento_faturamento text,
  cambio_contabilidade numeric,
  uf_origem text,
  uf_destino text,
  simples_nacional_sap text,
  optante_simples text,
  data_opcao_simples date,
  data_exclusao_simples date,
  material text,
  texto_breve_material text,
  numero_servico text,
  descricao_servico text,
  quantidade numeric,
  unidade_medida text,
  centro text,
  codigo_controle text,
  cfop text,
  documento_compras text,
  codigo_imposto text,
  moeda_documento text,
  base_icms numeric,
  valor_icms_total numeric,
  base_ipi numeric,
  valor_ipi numeric,
  valor_iss numeric,
  valor_inss numeric,
  base_pis numeric,
  aliquota_pis numeric,
  valor_pis numeric,
  base_cofins numeric,
  aliquota_cofins numeric,
  valor_cofins numeric,
  valor_difal numeric,
  valor_icms_part_dest numeric,
  valor_icms_icm3 numeric,
  base_ibs numeric,
  aliquota_ibs numeric,
  valor_ibs numeric,
  base_cbs numeric,
  aliquota_cbs numeric,
  valor_cbs numeric,
  total numeric,
  preco_liquido numeric,
  referencia_documento_origem text,
  item_documento_origem text,
  documento_vendas text,
  item_documento_vendas text,
  numero_pedido text,
  apelido_ativo text,
  direito_fiscal_icms text,
  direito_fiscal_ipi text,
  direito_fiscal_iss text,
  direito_fiscal_pis text,
  direito_fiscal_cofins text,
  situacao_tributaria_icms text,
  debito_posterior text,
  numero_documento_original text,
  item_referencia_nf text,
  pedido text,
  item_pedido text,
  centro_lucro text,
  codigo_conta_analitica_dc text,
  campos_extras jsonb,
  imported_at timestamptz not null default now()
);

create index if not exists idx_sap_zl0136_nf_numero_documento
  on public.sap_zl0136_nf (numero_documento_nove_posicoes);
create index if not exists idx_sap_zl0136_nf_chave_acesso
  on public.sap_zl0136_nf (chave_acesso);
create index if not exists idx_sap_zl0136_nf_documento_compras
  on public.sap_zl0136_nf (documento_compras);
create index if not exists idx_sap_zl0136_nf_pedido
  on public.sap_zl0136_nf (pedido);
create index if not exists idx_sap_zl0136_nf_material
  on public.sap_zl0136_nf (material);
create index if not exists idx_sap_zl0136_nf_data_documento
  on public.sap_zl0136_nf (data_documento);
create index if not exists idx_sap_zl0136_nf_cnpj
  on public.sap_zl0136_nf (cnpj_parceiro);

alter table public.sap_zl0136_nf enable row level security;

drop policy if exists "zl0136_nf_read" on public.sap_zl0136_nf;
create policy "zl0136_nf_read"
  on public.sap_zl0136_nf
  for select to authenticated
  using (
    public.has_role('admin')
    or exists (
      select 1
      from public.core_perfis p
      where p.id = (select auth.uid())::text
        and p.status = 'ativo'
        and p.sector_id in ('6', '7', '18')
    )
  );

drop policy if exists "zl0136_nf_insert" on public.sap_zl0136_nf;
create policy "zl0136_nf_insert"
  on public.sap_zl0136_nf
  for insert to authenticated
  with check (
    public.has_role('admin')
    or exists (
      select 1
      from public.core_perfis p
      where p.id = (select auth.uid())::text
        and p.status = 'ativo'
        and p.sector_id in ('6', '7', '18')
    )
  );

drop policy if exists "zl0136_nf_delete" on public.sap_zl0136_nf;
create policy "zl0136_nf_delete"
  on public.sap_zl0136_nf
  for delete to authenticated
  using (
    public.has_role('admin')
    or exists (
      select 1
      from public.core_perfis p
      where p.id = (select auth.uid())::text
        and p.status = 'ativo'
        and p.sector_id in ('6', '7', '18')
    )
  );

revoke all on table public.sap_zl0136_nf from anon;
revoke all on table public.sap_zl0136_nf from authenticated;
grant select, insert, delete on table public.sap_zl0136_nf to authenticated;
grant all on table public.sap_zl0136_nf to service_role;
revoke all on sequence public.sap_zl0136_nf_id_seq from anon;
grant usage, select on sequence public.sap_zl0136_nf_id_seq to authenticated, service_role;
