-- Controle de Estoque do Almoxarifado
--
-- Reproduz a faixa operacional da planilha sem duplicar as bases SAP.
-- O cálculo final permanece no frontend (src/lib/controleEstoque.ts); esta
-- migration entrega fatos agregados, parâmetros auditados e rastreabilidade.

create table public.almox_controle_estoque_config (
  id uuid primary key default gen_random_uuid(),
  centro text not null,
  janela_inicio date not null,
  janela_fim date,
  lead_time_padrao_dias numeric not null default 15,
  intervalo_compra_dias numeric not null default 30,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  updated_by text,
  constraint almox_controle_config_centro_chk check (btrim(centro) <> ''),
  constraint almox_controle_config_janela_chk check (janela_fim is null or janela_fim >= janela_inicio),
  constraint almox_controle_config_lead_chk check (lead_time_padrao_dias >= 0),
  constraint almox_controle_config_intervalo_chk check (intervalo_compra_dias >= 0)
);

comment on table public.almox_controle_estoque_config is
  'Parâmetros globais auditados da faixa operacional de estoque por centro.';

create unique index almox_controle_config_centro_ativo_uidx
  on public.almox_controle_estoque_config (centro)
  where ativo;
create index almox_controle_config_centro_idx
  on public.almox_controle_estoque_config (centro);
create index almox_controle_config_ativo_idx
  on public.almox_controle_estoque_config (ativo);

create table public.almox_controle_estoque_override (
  id uuid primary key default gen_random_uuid(),
  material text not null,
  centro text not null,
  tipo_gestao text,
  lead_time_dias numeric,
  intervalo_compra_dias numeric,
  estoque_minimo numeric,
  estoque_maximo numeric,
  quantidade_por_torre numeric,
  justificativa text not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  updated_by text,
  constraint almox_controle_override_material_chk check (btrim(material) <> ''),
  constraint almox_controle_override_centro_chk check (btrim(centro) <> ''),
  constraint almox_controle_override_lead_chk check (lead_time_dias is null or lead_time_dias >= 0),
  constraint almox_controle_override_intervalo_chk check (intervalo_compra_dias is null or intervalo_compra_dias >= 0),
  constraint almox_controle_override_minimo_chk check (estoque_minimo is null or estoque_minimo >= 0),
  constraint almox_controle_override_maximo_chk check (estoque_maximo is null or estoque_maximo >= 0),
  constraint almox_controle_override_faixa_chk check (
    estoque_minimo is null or estoque_maximo is null or estoque_maximo >= estoque_minimo
  ),
  constraint almox_controle_override_torre_chk check (
    quantidade_por_torre is null or quantidade_por_torre > 0
  ),
  constraint almox_controle_override_justificativa_chk check (
    not ativo or length(btrim(justificativa)) >= 5
  )
);

comment on table public.almox_controle_estoque_override is
  'Exceções por material/centro. Registros são inativados, nunca excluídos pela aplicação.';

create unique index almox_controle_override_material_centro_ativo_uidx
  on public.almox_controle_estoque_override (material, centro)
  where ativo;
create index almox_controle_override_material_idx
  on public.almox_controle_estoque_override (material);
create index almox_controle_override_centro_idx
  on public.almox_controle_estoque_override (centro);
create index almox_controle_override_ativo_idx
  on public.almox_controle_estoque_override (ativo);

create table public.almox_controle_estoque_auditoria (
  id bigint generated by default as identity primary key,
  entidade text not null,
  registro_id uuid not null,
  acao text not null,
  dados_anteriores jsonb,
  dados_novos jsonb,
  alterado_por text,
  alterado_em timestamptz not null default now(),
  constraint almox_controle_auditoria_entidade_chk check (
    entidade in ('almox_controle_estoque_config', 'almox_controle_estoque_override')
  ),
  constraint almox_controle_auditoria_acao_chk check (acao in ('INSERT', 'UPDATE'))
);

comment on table public.almox_controle_estoque_auditoria is
  'Histórico imutável de parâmetros e overrides do Controle de Estoque.';

create index almox_controle_auditoria_registro_idx
  on public.almox_controle_estoque_auditoria (entidade, registro_id, alterado_em desc);

create trigger almox_controle_config_updated_at
  before update on public.almox_controle_estoque_config
  for each row execute function public.tocar_updated_at();

create trigger almox_controle_override_updated_at
  before update on public.almox_controle_estoque_override
  for each row execute function public.tocar_updated_at();

create or replace function public.auditar_almox_controle_estoque()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_anterior jsonb;
  v_novo jsonb;
  v_registro_id uuid;
  v_alterado_por text;
begin
  if tg_op = 'INSERT' then
    v_anterior := null;
    v_novo := to_jsonb(new);
    v_registro_id := new.id;
  else
    v_anterior := to_jsonb(old);
    v_novo := to_jsonb(new);
    v_registro_id := new.id;
  end if;

  v_alterado_por := coalesce(
    v_novo ->> 'updated_by',
    v_novo ->> 'created_by',
    auth.uid()::text
  );

  insert into public.almox_controle_estoque_auditoria (
    entidade,
    registro_id,
    acao,
    dados_anteriores,
    dados_novos,
    alterado_por
  ) values (
    tg_table_name,
    v_registro_id,
    tg_op,
    v_anterior,
    v_novo,
    v_alterado_por
  );

  return new;
end;
$$;

revoke all on function public.auditar_almox_controle_estoque() from public, anon, authenticated;

create trigger almox_controle_config_auditoria
  after insert or update on public.almox_controle_estoque_config
  for each row execute function public.auditar_almox_controle_estoque();

create trigger almox_controle_override_auditoria
  after insert or update on public.almox_controle_estoque_override
  for each row execute function public.auditar_almox_controle_estoque();

alter table public.almox_controle_estoque_config enable row level security;
alter table public.almox_controle_estoque_override enable row level security;
alter table public.almox_controle_estoque_auditoria enable row level security;

create policy almox_controle_config_select
  on public.almox_controle_estoque_config
  for select to authenticated
  using (
    public.has_role('admin')
    or public.has_page_access('almox_controle_estoque')
    or public.has_page_access('almox_controle_estoque_editar')
  );

create policy almox_controle_config_insert
  on public.almox_controle_estoque_config
  for insert to authenticated
  with check (
    public.has_role('admin')
    or public.has_page_access('almox_controle_estoque_editar')
  );

create policy almox_controle_config_update
  on public.almox_controle_estoque_config
  for update to authenticated
  using (
    public.has_role('admin')
    or public.has_page_access('almox_controle_estoque_editar')
  )
  with check (
    public.has_role('admin')
    or public.has_page_access('almox_controle_estoque_editar')
  );

create policy almox_controle_override_select
  on public.almox_controle_estoque_override
  for select to authenticated
  using (
    public.has_role('admin')
    or public.has_page_access('almox_controle_estoque')
    or public.has_page_access('almox_controle_estoque_editar')
  );

create policy almox_controle_override_insert
  on public.almox_controle_estoque_override
  for insert to authenticated
  with check (
    public.has_role('admin')
    or public.has_page_access('almox_controle_estoque_editar')
  );

create policy almox_controle_override_update
  on public.almox_controle_estoque_override
  for update to authenticated
  using (
    public.has_role('admin')
    or public.has_page_access('almox_controle_estoque_editar')
  )
  with check (
    public.has_role('admin')
    or public.has_page_access('almox_controle_estoque_editar')
  );

create policy almox_controle_auditoria_select
  on public.almox_controle_estoque_auditoria
  for select to authenticated
  using (
    public.has_role('admin')
    or public.has_page_access('almox_controle_estoque')
    or public.has_page_access('almox_controle_estoque_editar')
  );

revoke all on public.almox_controle_estoque_config from anon;
revoke all on public.almox_controle_estoque_override from anon;
revoke all on public.almox_controle_estoque_auditoria from anon;
grant select, insert, update on public.almox_controle_estoque_config to authenticated;
grant select, insert, update on public.almox_controle_estoque_override to authenticated;
grant select on public.almox_controle_estoque_auditoria to authenticated;

insert into public.almox_controle_estoque_config (
  centro,
  janela_inicio,
  janela_fim,
  lead_time_padrao_dias,
  intervalo_compra_dias,
  ativo,
  created_by,
  updated_by
) values (
  'TEN2',
  date '2026-03-03',
  null,
  15,
  30,
  true,
  'migration:almox_controle_estoque',
  'migration:almox_controle_estoque'
);

create view public.vw_almox_controle_estoque
with (security_invoker = true)
as
with acesso as (
  select (
    public.has_role('admin')
    or public.has_page_access('almox_controle_estoque')
    or public.has_page_access('almox_controle_estoque_editar')
  ) as permitido
),
centros as (
  select distinct centro
  from public.sap_zl0024_stk
  where centro is not null and material is not null
),
limites_movimento as (
  select centro, min(data_lancamento) as inicio, max(data_lancamento) as fim
  from public.sap_mb51_mov
  where data_lancamento is not null
  group by centro
),
parametros as (
  select
    c.centro,
    coalesce(cfg.janela_inicio, lm.inicio) as janela_inicio,
    coalesce(cfg.janela_fim, lm.fim) as janela_fim,
    coalesce(cfg.lead_time_padrao_dias, 15::numeric) as lead_time_padrao_dias,
    coalesce(cfg.intervalo_compra_dias, 30::numeric) as intervalo_compra_dias,
    cfg.id as config_id,
    cfg.updated_at as config_updated_at
  from centros c
  left join limites_movimento lm on lm.centro = c.centro
  left join public.almox_controle_estoque_config cfg
    on cfg.centro = c.centro and cfg.ativo
),
parametros_dias as (
  select
    p.*,
    case
      when p.janela_inicio is null or p.janela_fim is null or p.janela_fim < p.janela_inicio then null
      else (
        select count(*)::integer
        from generate_series(p.janela_inicio, p.janela_fim, interval '1 day') dia
        where extract(isodow from dia) between 1 and 5
      )
    end as dias_uteis
  from parametros p
),
posicao as (
  select
    s.material,
    s.centro,
    max(s.txt_breve_material) as descricao,
    max(s.grupo_mercadorias) as categoria,
    max(s.aplicacao) as aplicacao,
    max(s.tipo_material) as tipo_material,
    max(s.umb) as umb,
    max(s.class_item) as curva_abc,
    sum(coalesce(s.quantidade, 0)) as saldo_total,
    sum(coalesce(s.quantidade, 0)) filter (
      where coalesce(s.deposito, '') not in (
        '0030','0070','0080','0100','0110','0120','0126','0201','0202','0203','0210'
      )
    ) as saldo_reposicao,
    sum(coalesce(s.valor_total, 0)) as valor_estoque,
    case
      when sum(coalesce(s.quantidade, 0)) <> 0
        then sum(coalesce(s.valor_total, 0)) / nullif(sum(coalesce(s.quantidade, 0)), 0)
      else avg(nullif(s.preco_medio, 0))
    end as preco_medio_sap,
    count(distinct s.deposito) as quantidade_depositos,
    jsonb_agg(
      jsonb_build_object(
        'deposito', s.deposito,
        'saldo', coalesce(s.quantidade, 0),
        'valor', coalesce(s.valor_total, 0),
        'preco_medio_sap', s.preco_medio,
        'inativo', coalesce(s.deposito, '') in (
          '0030','0070','0080','0100','0110','0120','0126','0201','0202','0203','0210'
        )
      ) order by s.deposito
    ) as depositos,
    max(s.imported_at) as estoque_importado_em
  from public.sap_zl0024_stk s
  where s.material is not null
  group by s.material, s.centro
),
movimentos_base as (
  select m.*, p.janela_inicio, p.janela_fim
  from public.sap_mb51_mov m
  join parametros_dias p on p.centro = m.centro
  where m.material is not null
    and m.data_lancamento between p.janela_inicio and p.janela_fim
),
movimentos as (
  select
    material,
    centro,
    coalesce(sum(qtd_um_registro) filter (where tipo_movimento in ('101','102')), 0) as entrada_quantidade,
    coalesce(sum(montante_mi) filter (where tipo_movimento in ('101','102')), 0) as entrada_valor,
    greatest(0, -coalesce(sum(qtd_um_registro) filter (where tipo_movimento in ('221','222')), 0)) as baixa_direta_quantidade,
    greatest(0, -coalesce(sum(montante_mi) filter (where tipo_movimento in ('221','222')), 0)) as baixa_direta_valor,
    greatest(0, -coalesce(sum(qtd_um_registro) filter (where tipo_movimento in ('311','312')), 0)) as producao_quantidade,
    greatest(0, -coalesce(sum(montante_mi) filter (where tipo_movimento in ('311','312')), 0)) as producao_valor,
    max(data_lancamento) as ultimo_movimento,
    max(imported_at) as movimentos_importados_em
  from movimentos_base
  group by material, centro
),
movimentos_mes as (
  select
    material,
    centro,
    date_trunc('month', data_lancamento)::date as mes,
    coalesce(sum(qtd_um_registro) filter (where tipo_movimento in ('101','102')), 0) as entrada,
    greatest(0, -coalesce(sum(qtd_um_registro) filter (where tipo_movimento in ('221','222','311','312')), 0)) as consumo,
    coalesce(sum(montante_mi) filter (where tipo_movimento in ('101','102')), 0) as valor_entrada,
    greatest(0, -coalesce(sum(montante_mi) filter (where tipo_movimento in ('221','222','311','312')), 0)) as valor_consumo
  from movimentos_base
  group by material, centro, date_trunc('month', data_lancamento)
),
series as (
  select
    material,
    centro,
    jsonb_agg(
      jsonb_build_object(
        'mes', mes,
        'entrada', entrada,
        'consumo', consumo,
        'valor_entrada', valor_entrada,
        'valor_consumo', valor_consumo
      ) order by mes
    ) as movimentos_mensais
  from movimentos_mes
  group by material, centro
),
rms_validas as (
  select *
  from public.sap_me5a_rc
  where material is not null
    and presente_ultima_carga is true
    and coalesce(eliminado, false) = false
    and coalesce(concluida, '') <> 'X'
),
rms as (
  select
    material,
    centro,
    count(*) as rms_abertas,
    sum(coalesce(qtd_solicitada, 0)) as rm_quantidade,
    jsonb_agg(
      jsonb_build_object(
        'ri', ri,
        'requisicao', requisicao_de_compra,
        'item', item_reqc,
        'data', data_da_solicitacao,
        'requisitante', requisitante,
        'quantidade', qtd_solicitada,
        'pedido', pedido,
        'deposito', deposito
      ) order by data_da_solicitacao desc nulls last, requisicao_de_compra
    ) as rms
  from rms_validas
  group by material, centro
),
recebimentos_pedido as (
  select
    material,
    centro,
    pedido,
    sum(qtd_um_registro) as quantidade_recebida,
    sum(montante_mi) as valor_recebido,
    max(data_lancamento) as ultima_data_recebimento
  from public.sap_mb51_mov
  where material is not null
    and pedido is not null
    and tipo_movimento in ('101','102')
  group by material, centro, pedido
),
pos_distintas as (
  select distinct on (material, coalesce(doc_compra, ''), coalesce(item, ''))
    material,
    cen_cen as centro,
    dep_dep as deposito,
    ri,
    reqc,
    item,
    doc_compra,
    data_doc,
    dt_remessa,
    data_migo,
    qtd_pedido,
    qtd_fornecida,
    valor_em_brl,
    fornecedor_nome,
    modificado_em
  from public.sap_zl0132_po
  where material is not null and doc_compra is not null
  order by material, coalesce(doc_compra, ''), coalesce(item, ''), modificado_em desc nulls last
),
pos_enriquecidas as (
  select
    po.*,
    greatest(coalesce(po.qtd_pedido, 0) - coalesce(po.qtd_fornecida, 0), 0) as quantidade_pendente,
    rec.quantidade_recebida,
    rec.valor_recebido,
    rec.ultima_data_recebimento
  from pos_distintas po
  left join recebimentos_pedido rec
    on rec.material = po.material
   and rec.centro is not distinct from po.centro
   and rec.pedido = po.doc_compra
),
pos as (
  select
    material,
    centro,
    count(*) filter (where quantidade_pendente > 0) as pos_abertas,
    sum(quantidade_pendente) as po_quantidade_pendente,
    sum(coalesce(quantidade_recebida, 0)) as quantidade_recebida,
    max(ultima_data_recebimento) as ultima_data_recebimento,
    jsonb_agg(
      jsonb_build_object(
        'ri', ri,
        'requisicao', reqc,
        'pedido', doc_compra,
        'item', item,
        'data', data_doc,
        'remessa_prevista', dt_remessa,
        'data_migo', data_migo,
        'fornecedor', fornecedor_nome,
        'deposito', deposito,
        'quantidade_pedida', qtd_pedido,
        'quantidade_fornecida', qtd_fornecida,
        'quantidade_pendente', quantidade_pendente,
        'valor_brl', valor_em_brl,
        'quantidade_recebida_mb51', quantidade_recebida,
        'ultima_data_recebimento', ultima_data_recebimento
      ) order by data_doc desc nulls last, doc_compra
    ) as pedidos
  from pos_enriquecidas
  group by material, centro
),
bom_opcoes_distintas as (
  select distinct cod_sap as material, projeto, qtd_por_torre
  from public.vw_proj_bom_arvore
  where cod_sap is not null and btrim(cod_sap) <> '' and qtd_por_torre is not null
),
bom as (
  select
    material,
    case
      when count(distinct projeto) = 1 and count(distinct qtd_por_torre) = 1 then max(qtd_por_torre)
      else null
    end as quantidade_por_torre_automatica,
    count(distinct projeto) as quantidade_projetos,
    jsonb_agg(
      jsonb_build_object('projeto', projeto, 'quantidade_por_torre', qtd_por_torre)
      order by projeto, qtd_por_torre
    ) as opcoes_quantidade_por_torre
  from bom_opcoes_distintas
  group by material
)
select
  posicao.material,
  posicao.centro,
  posicao.descricao,
  posicao.categoria,
  posicao.aplicacao,
  posicao.tipo_material,
  coalesce(ov.tipo_gestao, 'NAO_DEFINIDO') as tipo_gestao,
  posicao.umb,
  posicao.curva_abc,
  posicao.saldo_total,
  coalesce(posicao.saldo_reposicao, 0) as saldo_reposicao,
  posicao.valor_estoque,
  posicao.preco_medio_sap,
  posicao.quantidade_depositos,
  posicao.depositos,
  pd.janela_inicio,
  pd.janela_fim,
  pd.dias_uteis,
  coalesce(ov.lead_time_dias, pd.lead_time_padrao_dias) as lead_time_dias,
  coalesce(ov.intervalo_compra_dias, pd.intervalo_compra_dias) as intervalo_compra_dias,
  coalesce(m.entrada_quantidade, 0) as entrada_quantidade,
  coalesce(m.entrada_valor, 0) as entrada_valor,
  coalesce(m.baixa_direta_quantidade, 0) as baixa_direta_quantidade,
  coalesce(m.baixa_direta_valor, 0) as baixa_direta_valor,
  coalesce(m.producao_quantidade, 0) as producao_quantidade,
  coalesce(m.producao_valor, 0) as producao_valor,
  coalesce(m.baixa_direta_quantidade, 0) + coalesce(m.producao_quantidade, 0) as consumo_total,
  coalesce(m.baixa_direta_valor, 0) + coalesce(m.producao_valor, 0) as consumo_valor,
  coalesce(sr.movimentos_mensais, '[]'::jsonb) as movimentos_mensais,
  coalesce(r.rms_abertas, 0) as rms_abertas,
  coalesce(r.rm_quantidade, 0) as rm_quantidade,
  coalesce(r.rms, '[]'::jsonb) as rms,
  coalesce(po.pos_abertas, 0) as pos_abertas,
  coalesce(po.po_quantidade_pendente, 0) as po_quantidade_pendente,
  coalesce(po.quantidade_recebida, 0) as quantidade_recebida,
  po.ultima_data_recebimento,
  coalesce(po.pedidos, '[]'::jsonb) as pedidos,
  coalesce(ov.quantidade_por_torre, bom.quantidade_por_torre_automatica) as quantidade_por_torre,
  coalesce(bom.quantidade_projetos, 0) as quantidade_projetos,
  coalesce(bom.opcoes_quantidade_por_torre, '[]'::jsonb) as opcoes_quantidade_por_torre,
  ov.estoque_minimo as estoque_minimo_override,
  ov.estoque_maximo as estoque_maximo_override,
  ov.id as override_id,
  ov.justificativa as override_justificativa,
  ov.updated_at as override_updated_at,
  ov.updated_by as override_updated_by,
  (ov.id is not null) as tem_override,
  rep.janela_inicio as sisten_janela_inicio,
  rep.janela_fim as sisten_janela_fim,
  rep.consumo_total as sisten_consumo_total,
  rep.consumo_diario as sisten_consumo_diario,
  rep.lote_p90 as sisten_lote_p90,
  rep.adi as sisten_adi,
  rep.cv2 as sisten_cv2,
  rep.lead_dias as sisten_lead_dias,
  rep.lead_proprio as sisten_lead_proprio,
  posicao.estoque_importado_em,
  m.movimentos_importados_em,
  m.ultimo_movimento,
  pd.config_id,
  pd.config_updated_at
from posicao
join parametros_dias pd on pd.centro = posicao.centro
cross join acesso a
left join movimentos m on m.material = posicao.material and m.centro = posicao.centro
left join series sr on sr.material = posicao.material and sr.centro = posicao.centro
left join rms r on r.material = posicao.material and r.centro = posicao.centro
left join pos po on po.material = posicao.material and po.centro = posicao.centro
left join bom on bom.material = posicao.material
left join public.almox_controle_estoque_override ov
  on ov.material = posicao.material and ov.centro = posicao.centro and ov.ativo
left join public.vw_estoque_reposicao rep on rep.material = posicao.material
where a.permitido;

comment on view public.vw_almox_controle_estoque is
  'Uma linha por material/centro com posição SAP, movimentos, RMs, POs, recebimentos, BOM e parâmetros auditados.';

revoke all on public.vw_almox_controle_estoque from anon;
grant select on public.vw_almox_controle_estoque to authenticated;
