-- Migration: Criação da tabela de importação da planilha ME2L (Pedidos de Compra)
-- Data: 2026-09-12
--
-- ME2L é o relatório SAP de acompanhamento de pedidos de compra (itens de PO com
-- requisição, requisitante, valores e status de liberação). "Nº acompanhamento"
-- é o identificador único de linha no SAP e é usado como chave de deduplicação
-- na reimportação (a planilha não traz um número de item de PO separado).

CREATE TABLE IF NOT EXISTS public.sap_me2l_pedido (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacao_compras text,
  centro text,
  material text,
  texto_breve text,
  codigo_eliminacao text,
  deposito text,
  data_documento date,
  n_acompanhamento text NOT NULL,
  requisicao_compra text,
  documento_compras text NOT NULL,
  fornecedor text,
  requisitante text,
  criado_por text,
  qtd_pedido numeric,
  a_fornecer_qtd numeric,
  um_pedido text,
  valor_liquido_pedido numeric,
  moeda text,
  unidade_preco text,
  contrato_basico text,
  grupo_liberacao text,
  codigo_imposto text,
  codigo_liberacao text,
  grupo_mercadorias text,
  imported_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE (n_acompanhamento)
);

CREATE INDEX IF NOT EXISTS idx_sap_me2l_pedido_documento ON public.sap_me2l_pedido(documento_compras);
CREATE INDEX IF NOT EXISTS idx_sap_me2l_pedido_material ON public.sap_me2l_pedido(material);
CREATE INDEX IF NOT EXISTS idx_sap_me2l_pedido_fornecedor ON public.sap_me2l_pedido(fornecedor);
CREATE INDEX IF NOT EXISTS idx_sap_me2l_pedido_data ON public.sap_me2l_pedido(data_documento);

ALTER TABLE public.sap_me2l_pedido ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sap_me2l_pedido_read" ON public.sap_me2l_pedido;
CREATE POLICY "sap_me2l_pedido_read" ON public.sap_me2l_pedido
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "sap_me2l_pedido_write" ON public.sap_me2l_pedido;
CREATE POLICY "sap_me2l_pedido_write" ON public.sap_me2l_pedido
  FOR ALL TO authenticated
  USING (public.has_role('admin') OR public.has_role('coordenador_suprimentos') OR public.has_role('comprador'))
  WITH CHECK (public.has_role('admin') OR public.has_role('coordenador_suprimentos') OR public.has_role('comprador'));

GRANT ALL ON TABLE public.sap_me2l_pedido TO anon, authenticated, service_role;
