-- ZF0076: notas fiscais de compras relacionadas a pedidos de compra.
-- Cada importação é uma fotografia completa do export SAP: remove a carga
-- anterior e insere somente as linhas válidas do novo arquivo.

create table if not exists public.sap_zf0076_nf_po (
  id bigint generated by default as identity primary key,
  documento_compra text not null,
  item_pedido text not null,
  data_aprovacao date,
  centro text,
  ap text,
  preco text,
  man text,
  mbl text,
  dat text,
  mt text,
  material text,
  texto_breve text,
  requisitante text,
  numero_acompanhamento text,
  contrato text,
  item_contrato text,
  data_criacao date,
  hora text,
  criado_por text,
  requisicao_compra text,
  item_requisicao text,
  codigo_tipo text,
  numero_documento text,
  ano_documento text,
  empresa text,
  moeda_documento text,
  data_documento date,
  data_lancamento date,
  documento_referencia text,
  referencia_documento text,
  referencia_nf text,
  data_entrada date,
  nome_usuario text,
  item_faturamento text,
  quantidade numeric,
  unidade_medida text,
  quantidade_upp numeric,
  unidade_medida_upp text,
  debito_credito text,
  montante numeric,
  moeda_montante text,
  taxa_cambio numeric,
  indicador_in text,
  custo_complementar_aquisicao numeric,
  codigo_imposto text,
  imposto text,
  moeda_imposto text,
  montante_bruto numeric,
  moeda_bruto text,
  iva_wmwst numeric,
  moeda_iva text,
  tipo_condicao text,
  tipo_documento text,
  tipo_operacao text,
  local_negocios text,
  numero_serie text,
  domicilio_fiscal_fornecedor text,
  fornecedor text,
  nome_fornecedor text,
  fornecedor_alternativo text,
  nome_fornecedor_alternativo text,
  nome_fornecedor_2 text,
  nome_fornecedor_3 text,
  nome_fornecedor_4 text,
  local_fornecedor text,
  regiao_fornecedor text,
  pais_fornecedor text,
  codigo_postal_fornecedor text,
  domicilio_fiscal text,
  id_fiscal_1 text,
  id_fiscal_2 text,
  id_fiscal_iva text,
  item_nf text,
  material_nf text,
  blp text,
  referencia_faturamento text,
  campos_extras jsonb,
  imported_at timestamptz not null default now()
);

create index if not exists idx_sap_zf0076_nf_po_documento_compra
  on public.sap_zf0076_nf_po (documento_compra);
create index if not exists idx_sap_zf0076_nf_po_numero_documento
  on public.sap_zf0076_nf_po (numero_documento);
create index if not exists idx_sap_zf0076_nf_po_data_documento
  on public.sap_zf0076_nf_po (data_documento);
create index if not exists idx_sap_zf0076_nf_po_fornecedor
  on public.sap_zf0076_nf_po (fornecedor);
create index if not exists idx_sap_zf0076_nf_po_material
  on public.sap_zf0076_nf_po (material);
create index if not exists idx_sap_zf0076_nf_po_referencia_nf
  on public.sap_zf0076_nf_po (referencia_nf);

alter table public.sap_zf0076_nf_po enable row level security;

drop policy if exists "zf0076_nf_po_read" on public.sap_zf0076_nf_po;
create policy "zf0076_nf_po_read"
  on public.sap_zf0076_nf_po
  for select to authenticated
  using (
    public.has_role('admin')
    or exists (
      select 1
      from public.core_perfis p
      where p.id = (select auth.uid())::text
        and p.status = 'ativo'
        and p.sector_id in ('6', '7', '18')
    )
  );

drop policy if exists "zf0076_nf_po_write" on public.sap_zf0076_nf_po;
create policy "zf0076_nf_po_write"
  on public.sap_zf0076_nf_po
  for all to authenticated
  using (
    public.has_role('admin')
    or exists (
      select 1
      from public.core_perfis p
      where p.id = (select auth.uid())::text
        and p.status = 'ativo'
        and p.sector_id in ('6', '7', '18')
    )
  )
  with check (
    public.has_role('admin')
    or exists (
      select 1
      from public.core_perfis p
      where p.id = (select auth.uid())::text
        and p.status = 'ativo'
        and p.sector_id in ('6', '7', '18')
    )
  );

grant select on table public.sap_zf0076_nf_po to authenticated;
grant insert, delete on table public.sap_zf0076_nf_po to authenticated;
grant all on table public.sap_zf0076_nf_po to service_role;
grant usage, select on sequence public.sap_zf0076_nf_po_id_seq to authenticated, service_role;
